---
permalink: online-help/concept-introduction-to-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Unified Manager ermöglicht das Monitoring und Management des Systemzustands sowie der Performance Ihrer ONTAP Storage-Systeme über eine einheitliche Benutzeroberfläche. 
---
= Einführung in OnCommand Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Unified Manager ermöglicht das Monitoring und Management des Systemzustands sowie der Performance Ihrer ONTAP Storage-Systeme über eine einheitliche Benutzeroberfläche.

Unified Manager bietet folgende Funktionen:

* Bestandsaufnahme, Monitoring und Benachrichtigungen für Systeme, die mit der ONTAP Software installiert sind
* Dashboards zur Anzeige von Kapazität, Verfügbarkeit, Schutz und Performance-Zustand der Umgebung
* Erweiterte Alarmfunktionen, Ereignisse und Schwellenwertsinfrastruktur.
* Zeigt detaillierte Diagramme an, die Workload-Aktivitäten im Zeitverlauf darstellen, einschließlich IOPS (Vorgänge), MB/s (Durchsatz), Latenz (Reaktionszeit), Auslastung, Performance-Kapazität und Cache-Verhältnis.
* Identifiziert Workloads, die zu viel Cluster-Komponenten nutzen, und Workloads, deren Performance durch den gesteigerten Durchsatz beeinträchtigt wird
* Enthält vorgeschlagene Korrekturmaßnahmen, die zur Behebung bestimmter Vorfälle und Ereignisse durchgeführt werden können.
* Integration in OnCommand Workflow Automation zur Ausführung automatisierter Workflows

