---
permalink: online-help/reference-lun-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite „Performance/LUN Information“ können Sie eine Liste der physischen und logischen Attribute der LUN anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen. 
---
= Informationen zu Performance/LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Performance/LUN Information“ können Sie eine Liste der physischen und logischen Attribute der LUN anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen.



== LUN-Attribute

* * WWN*
+
Der WWN (World Wide Name) der LUN.

* *Pfad*
+
Der vollständige Pfad der LUN, beispielsweise `/vol/vol1/lun1`.

* *Ausrichtung*
+
Zeigt den Ausrichtungsstatus der LUN an. Mögliche Werte:

+
** Nicht zugeordnet
** Ausgerichtet
** Falsch Ausgerichtet
** Möglicherweise falsch ausgerichtet
** Unbestimmt


* * Kapazität (frei/gesamt)*
+
Der gesamte verfügbare Speicher auf der LUN, in Gigabyte und der derzeit verfügbaren Menge an Speicherplatz.

* *Lautstärke*
+
Der Name des Volumes, zu dem die LUN gehört. Sie können auf den Namen klicken, um die Volume-Details auf der Seite Performance/Volume Explorer anzuzeigen.

* *Storage Virtual Machine*
+
Der Name der SVM, der die LUN angehört. Sie können auf der Seite „Performance/SVM Explorer“ auf den Namen klicken, um SVM-Details anzuzeigen.

* *Knoten*
+
Der Name des Node, auf dem sich die LUN befindet. Sie können auf den Namen klicken, um Node-Details auf der Seite Performance/Node Explorer anzuzeigen.

* * Cluster*
+
Der Name des Clusters, zu dem die LUN gehört. Sie können auf den Namen klicken, um in der Seite „Performance/Cluster Explorer“ Cluster-Details anzuzeigen.

* *Bundesland*
+
Der Zustand der LUN. Gültige Status können „Online“, „Offline“, „NV-Fehler“, „Speicherplatz-Fehler“ und „Foreign-lun-Fehler“ sein.

* * Zugeordnet*
+
Gibt an, ob die LUN einer Initiatorgruppe zugeordnet ist (true), oder nicht (false).


