---
permalink: online-help/reference-event-setup-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite „Ereignisse konfigurieren/managen“ wird die Liste der deaktivierten Ereignisse angezeigt, und es werden Informationen wie der zugehörige Objekttyp und der Schweregrad des Ereignisses angezeigt. Sie können auch Aufgaben wie Deaktivieren oder Aktivieren von Ereignissen global ausführen. 
---
= Seite „Ereignisse konfigurieren/managen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Ereignisse konfigurieren/managen“ wird die Liste der deaktivierten Ereignisse angezeigt, und es werden Informationen wie der zugehörige Objekttyp und der Schweregrad des Ereignisses angezeigt. Sie können auch Aufgaben wie Deaktivieren oder Aktivieren von Ereignissen global ausführen.

Sie können diese Seite nur aufrufen, wenn Sie die Rolle „OnCommand-Administrator“ oder „Storage-Administrator“ besitzen.



== Befehlsschaltflächen

Mit den Befehlsschaltflächen können Sie die folgenden Aufgaben für ausgewählte Ereignisse ausführen:

* *Deaktivieren*
+
Öffnet das Dialogfeld Ereignisse deaktivieren, mit dem Sie Ereignisse deaktivieren können.

* *Aktivieren*
+
Aktiviert ausgewählte Ereignisse, die Sie zuvor deaktiviert hatten.

* *EMS Events abonnieren*
+
Öffnet das Dialogfeld „EMS-Ereignisse abonnieren“, in dem Sie spezielle EMS-Ereignisse (Event Management System) aus den von Ihnen überwachten Clustern abonnieren können. Das EMS sammelt Informationen über Ereignisse, die auf dem Cluster auftreten. Wenn eine Benachrichtigung für ein abonniertes EMS-Ereignis erhalten wird, wird ein Unified Manager-Ereignis mit dem entsprechenden Schweregrad generiert.

* *Einstellungen Für Die Ereignisaufbewahrung*
+
Öffnet das Dialogfeld „Ereignisaufbewahrungseinstellungen“, in dem Sie den Aufbewahrungszeitraum festlegen können, nach dem die Informationen, aufgelösten und veralteten Ereignisse vom Verwaltungsserver entfernt werden. Der Standardwert für die Aufbewahrung ist 180 Tage.





== Listenansicht

In der Listenansicht werden Informationen zu deaktivierten Ereignissen (im Tabellenformat) angezeigt. Mit den Spaltenfiltern können Sie die angezeigten Daten anpassen.

* *Veranstaltung*
+
Zeigt den Namen des Ereignisses an, das deaktiviert ist.

* *Severity*
+
Zeigt den Schweregrad des Ereignisses an. Der Schweregrad kann kritisch, Fehler, Warnung oder Informationen sein.

* *Quelltyp*
+
Zeigt den Quelltyp an, für den das Ereignis generiert wird.


