---
permalink: online-help/reference-lun-events.html 
sidebar: sidebar 
keywords:  
summary: LUN-Ereignisse liefern Ihnen Informationen zum Status Ihrer LUNs, sodass Sie ein Monitoring auf potenzielle Probleme durchführen können. Ereignisse sind nach Impact Area gruppiert und umfassen den Ereignis- und Trap-Namen, den Impact-Level, den Quelltyp und den Schweregrad. 
---
= LUN-Ereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN-Ereignisse liefern Ihnen Informationen zum Status Ihrer LUNs, sodass Sie ein Monitoring auf potenzielle Probleme durchführen können. Ereignisse sind nach Impact Area gruppiert und umfassen den Ereignis- und Trap-Namen, den Impact-Level, den Quelltyp und den Schweregrad.



== Impact Area: Verfügbarkeit

Ein Sternchen (*) identifiziert EMS-Ereignisse, die in Unified Manager-Ereignisse konvertiert wurden.

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
LUN Offline(ocumEvtLunOffline)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN wurde zerstört *
 a| 
Ereignis
 a| 
LUN
 a| 
Informationsdaten



 a| 
Einzel aktiv Pfad für den Zugriff auf LUN(occumEvtLunSingleActivePath)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
Keine aktiven Pfade zum Zugriff auf die LUN (occumEvtLunNoteAbable)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
Keine optimierten Pfade zum Zugriff auf LUN(ocumEvtLunOptimizedPathInaktiv)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
Keine Pfade zum LUN vom HA Partner(ocumEvtLunHaPathInaktiv)
 a| 
Dar
 a| 
LUN
 a| 
Warnung

|===


== Impact Area: Kapazität

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
Unzureichender Speicherplatz für LUN Snapshot Kopie (ocumEvtLunSnapshotmöglich)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung

|===


== Impact Area: Performance

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
Unterschreiten kritischer Schwellenwert für LUN-IOPS (OktumLunIopsVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
Unterschreitr. LUN IOPS-Warnungsschwellenwert (ocumLunIopsWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
Unterschreiten kritischen Schwellenwert für LUN/MB/s (ocumLunMbpsVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN Mbps: Überschreitung des Warnungsschwellenwerts (ocumLunMbpsWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz ms/op Critical Threshold undurchbrochen (ocumLunenzIncident)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz ms/op Warnschwellenwert nicht eingehalten (ocumLunLatenzWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und IOPS – kritischer Schwellenwert – nicht erreicht (ocumLunLatenzenIopsVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und IOPS - Überschreitung des Warnungsschwellenwerts (ocumLunLatenzIopsWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und MB/s kritischer Schwellenwert überschritten (ocumLunenzLatency MbpsVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und MB/s-Warnung nicht erreichender Schwellenwert (ocumLunenzMbpsWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und aggregierte Performance Verwendete Kapazität – kritischer Schwellenwert nicht erreicht (ocumLunenzyAggregatePerfkapazitätUsedVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und aggregierte Performance Verwendete Kapazität – Warnung nicht erreichter Schwellenwert (ocumLunenzAggregatePerfkapazitätUsedWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und aggregierte Auslastung kritischer Schwellenwert überschritten (ocumLunenzAggregateUtilizationVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und Aggregat-Auslastung Warnschwellenwert nicht erreicht (ocumLunenzAggregateUtilizationWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und Node-Performance: Verwendete Kapazität – kritischer Schwellenwert nicht erreicht (ocumLunenzyNodePerfdataPerformance UsedIncident)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und Node-Performance: Verwendete Kapazität – Warnung: Nicht erreichter Schwellenwert (ocumLunenzyNodePerfkapazitätUsedWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und Node-Performance: Verwendete Kapazität – Übernahme kritischer Schwellenwert verletzt (ocumLunLatencyAggregatePerfkapazitätUseTakeoverIncident)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und Node-Performance: Verwendete Kapazität – Übernahmewarnschwellenwert verletzt (ocumLunLatenAggregatePerfkapazitätUseTakeoverWarning)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
LUN-Latenz und Node-Auslastung – kritischer Schwellenwert – nicht erreicht (ocumLunLatenzenNodeUtilizationVorfall)
 a| 
Vorfall
 a| 
LUN
 a| 
Kritisch



 a| 
LUN-Latenz und Node-Auslastung Warnung nicht erreichender Schwellenwert (ocumLunenzNodeUtilizationWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
QoS LUN Max. IOPS Warnschwellenwert nicht erreicht (ocumQosLunMaxIopsWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung



 a| 
QoS LUN Max. Mbit/s Warnschwellenwert überschritten (ocumQosLunMaxMbpsWarnung)
 a| 
Dar
 a| 
LUN
 a| 
Warnung

|===