---
permalink: online-help/reference-volume-events.html 
sidebar: sidebar 
keywords:  
summary: Volume-Ereignisse liefern Informationen zum Status von Volumes, mit denen Sie auf potenzielle Probleme überwachen können. Die Ereignisse sind nach dem Impact-Bereich gruppiert und umfassen den Event-Namen, den Trap-Namen, den Impact-Level, den Quelltyp und den Schweregrad. 
---
= Volume-Ereignisse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Volume-Ereignisse liefern Informationen zum Status von Volumes, mit denen Sie auf potenzielle Probleme überwachen können. Die Ereignisse sind nach dem Impact-Bereich gruppiert und umfassen den Event-Namen, den Trap-Namen, den Impact-Level, den Quelltyp und den Schweregrad.

Ein Sternchen (*) identifiziert EMS-Ereignisse, die in Unified Manager-Ereignisse konvertiert wurden.



== Impact Area: Verfügbarkeit

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
Volumenbeschränkungen (occumEvtVolumeRestricted)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume Offline(ocumEvtVolumeOffline)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Datenträger teilweise verfügbar(occumEvtVolumePartiallyverfügbar)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Volumen abgehängt (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume angehängt(nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume neu eingebunden (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume Junction Path Inaktiv (ocumEvtVolumeJunctionPathInaktiv)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Automatische Volumengröße aktiviert (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Automatische Volume-Größe deaktiviert (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Automatische Volumengröße maximale Kapazität geändert(nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Größe der automatischen Volume-Größe geändert (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten

|===


== Impact Area: Kapazität

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
Volume-Speicherplatz mit Thin Provisioning (ozumThinProvisionVolumeSpaceAtFestplatten)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Voll Volume-Speicherplatz(occumEvtVolumeFull)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Volume fast voll (ocumEvtVolumeNearline)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Logischer Speicherplatz des Volume voll * (VolumeLogicalSpaceFull)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Logischer Speicherplatz des Volume fast voll * (VolumeLogicalSpaceNearlyFull)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Logischer Speicherplatz des Volume normal *(VolumeLogicalSpaceAllOK)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume Snapshot Reserve voll(ocumEvtSnapshotvoll)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Zu viele Snapshot-Kopien (ocumEvtSnapshotTooManche)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Volume Qtree Kontingent überengagiert (occumEvtVolumeQtreeQuotaÜberengagiert)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Volume Qtree Kontingent fast überengagiert (ocumEvtVolumeQtreeQuotaAlmostÜberengagiert)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volumenwachstumsrate anormal (ocumEvtVolumeGrowth RowthRateAbnormal)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Tage bis voll (ocumEvtVolumeTagesUntilFullSoon)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Volume Space Guarantee deaktiviert(nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume-Space-Garantie Aktiviert (Nicht Zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume-Space-Garantie geändert(nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume Snapshot Reserve – Tage bis voll (ocumEvtVolumeSnapshotReserviertDaysUntilFullSoon)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
FlexGroup-Komponenten haben Raumprobleme *(FlexGroupInhaltHaveSpaceIssues)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
FlexGroup-Komponenten Raumstatus alles OK *(flexGruppeKonstitelenSpaceStatusAllOK)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
FlexGroup-Bestandteile haben Inodes-Probleme *(flexGroupKonstitutionenHaveInodesIssues)
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
FlexGroup-Komponenten inodes Status alles OK *(flexGroupConstitutionenInodesStatusAllOK)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Fehler bei der automatischen WAFL-Volume-Größe *
 a| 
Dar
 a| 
Datenmenge
 a| 
Fehler



 a| 
Automatische WAFL-Volume-Größe abgeschlossen *
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten

|===


== Impact Area: Konfiguration

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
Volumen umbenannt(nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Ermittelte Volumes (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten



 a| 
Volume gelöscht (nicht zutreffend)
 a| 
Ereignis
 a| 
Datenmenge
 a| 
Informationsdaten

|===


== Impact Area: Performance

|===
| Ereignisname (Trap-Name) | Auswirkungen | Typ der Quelle | Schweregrad 


 a| 
QoS Volume Max. IOPS Warnschwellenwert nicht erreicht (ocumQosVolumeMaxIopsWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
QoS Volume Max Mbps Warnungsschwellenwert überschritten (ocumQosVolumeMaxMbpsWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
QoS Volume Max. IOPS/TB Warnschwellenwert nicht erreicht (ocumQosVolumeMaxIopsPerTbWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Unterschreiten des kritischen Schwellenwerts für Volume-IOPS (OktumVolumeIopsVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Unterschreitr. Volume IOPS-Warnungsschwellenwert (ocumVolumeIopsWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Unterschreiten kritischen Schwellenwert für Volume-MB/s (ocumVolumeMbpsVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume Mbps Warnungsschwellenwert überschritten (ocumVolumeMbpsWarnung )
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz ms/op kritischer Schwellenwert – nicht überschritten (OktumVolumeLatenVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume-Latenz ms/op Warnungsschwellenwert nicht überschritten (ocumVolumeLatencyWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume Cache Miss-Verhältnis – kritischer Schwellenwert überschritten (ocumVolumeCacheMissRatioVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume Cache Miss Ratio Warnung nicht überschritten (ocumVolumeCacheMissRatioWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz und IOPS – kritischer Schwellenwert – nicht erreicht (ocumVolumeLatencyIopsVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Nicht erreichender Volume-Latenz und IOPS -Warnungsschwellenwert (ocumVolumeLatencyIopsWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Nicht erreichender Volume-Latenz und MB/s-kritischer Schwellenwert (ocumVolumeLatencyMbpsVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Nicht erreichender Volume-Latenz und MB/s-Warnungsschwellenwert (ocumVolumeLatencyMbpsWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz und aggregierte Performance Verwendete Kapazität – kritischer Schwellenwert nicht erreicht (ocumVolumeLatencyAggregatePerfkapazitätUsedVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume-Latenz und aggregierte Performance Verwendete Kapazität – Warnung: Nicht erreichter Schwellenwert (ocumVolumeLatencyAggregatePerfkapazitätUsedWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz und aggregierte Auslastung kritischer Schwellenwert überschritten (ocumVolumeLatenAggregateUtilizationVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume-Latenz und Aggregatauslastung Warnschwellenwert nicht erreicht (ocumVolumeLatenAggregateUtilizationWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz und Node-Performance: Verwendete Kapazität – kritischer Schwellenwert nicht erreicht (ocumVolumeLatencyNodePerfkapazitätBenutzerfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume-Latenz und Node-Performance: Verwendete Kapazität – Warnung: Nicht erreichter Schwellenwert (ocumVolumeLatencyNodePerformance-FunktionenWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz und Node-Performance: Verwendete Kapazität – Übernahme kritischer Schwellenwert verletzt (ocumVolumeLatencyAggregatePerfkapazitätUseTakeoverVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Volume-Latenz und Node-Performance: Verwendete Kapazität – Überschreitung der Schwellenberührte Überschreitung (VolumeLatencyAggregatePerfkapazitätUseTakeoverWarning)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung



 a| 
Volume-Latenz und Node-Auslastung – kritischer Schwellenwert – nicht erreicht (ocumVolumeLatencyNotilationVorfall)
 a| 
Vorfall
 a| 
Datenmenge
 a| 
Kritisch



 a| 
Nicht erreichender Schwellenwert für Volume-Latenz und Node-Auslastung (ocumVolumeLatencyNodeUtilizationWarnung)
 a| 
Dar
 a| 
Datenmenge
 a| 
Warnung

|===