---
permalink: online-help/reference-constituent-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: Mithilfe der Seite Informationen zum Performance/konstituierenden Volume können Sie eine Liste der physischen und logischen Attribute des FlexGroup-Volume anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen. 
---
= Informationsseite zum Performance-/konstituierenden Volumen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe der Seite Informationen zum Performance/konstituierenden Volume können Sie eine Liste der physischen und logischen Attribute des FlexGroup-Volume anzeigen. Diese Informationen könnten bei der Beantwortung von Fragen zur Leistungsfähigkeit helfen.



== Attribute des konstituierenden Volumes

* *Typ*
+
Typ der Komponente, entweder Lesen/Schreiben (RW) oder Datensicherung (DP).

* *Stil*
+
Stil des Volume, es handelt sich um ein zusammengehörige Volume eines FlexGroup Volume.

* * Cluster*
+
Der Name des Clusters, zu dem das FlexGroup-Teilvolume gehört. Sie können auf den Namen klicken, um in der Seite „Performance/Cluster Explorer“ Cluster-Details anzuzeigen.

* * Aggregat*
+
Der Name des Aggregats, auf dem sich das FlexGroup-Teilvolume befindet. Sie können auf den Namen klicken, um aggregierte Details auf der Seite „Performance/Aggregate Explorer“ anzuzeigen.

* *FlexGroup*
+
Der Name des FlexGroup Volume, zu dem diese Komponente gehört. Sie können auf den Namen klicken, um Details zu FlexGroup-Volumes auf der Seite „Performance/FlexGroup Explorer“ anzuzeigen.

* *Storage Virtual Machine*
+
Der Name der SVM, der das FlexGroup-Teilvolume angehört. Sie können auf der Seite „Performance/SVM Explorer“ auf den Namen klicken, um SVM-Details anzuzeigen.

* *Tiering-Richtlinie*
+
Die Tiering-Richtlinie für das Volume. Die Richtlinie wirkt sich nur dann aus, wenn das Volume auf einem FabricPool Aggregat bereitgestellt wird. Folgende Richtlinien stehen zur Verfügung:

+
** Keine. Die Daten für dieses Volume verbleiben immer auf der Performance-Tier.
** Nur Snapshot. Nur Snapshot Daten werden automatisch in die Cloud-Tier verschoben. Alle anderen Daten verbleiben in der Performance-Tier.
** Backup: Bei Datensicherungs-Volumes werden alle übertragenen Benutzerdaten in der Cloud-Tier gestartet, aber bei späteren Client-Lesevorgängen kann es dazu kommen, heiße Daten in die Performance-Tier zu verschieben.
** Automatisch. Daten auf diesem Volume werden automatisch zwischen Performance-Tier und Cloud-Tier verschoben, wenn ONTAP feststellt, dass die Daten „`Hot`“ oder „`Cold`“ sind.


* *RAID-Typ*
+
Der Redundanztyp, der auf dem Aggregat, in dem sich diese Komponente befindet, verwendet wird. Mögliche Typen:

+
** RAID0
** RAID4
** RAID-DP
** RAID-TEC


* * Kapazität (frei/gesamt)*
+
Den insgesamt verfügbaren Storage der Komponente in Gigabyte sowie die derzeit verfügbare Menge an Speicherplatz.


