---
permalink: online-help/reference-types-of-performance-counter-charts.html 
sidebar: sidebar 
keywords:  
summary: Es gibt Standard-Performance-Diagramme, in denen die Zählerwerte für das ausgewählte Speicherobjekt angezeigt werden. In jedem der Counter-Diagramme werden die Gesamtwerte angezeigt, die in Lese-, Schreib- und andere Kategorien unterteilt sind. Darüber hinaus zeigen einige Counter-Diagramme zusätzliche Details an, wenn das Diagramm in der Zoom-Ansicht angezeigt wird. 
---
= Arten von Performance-Zählerdiagrammen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt Standard-Performance-Diagramme, in denen die Zählerwerte für das ausgewählte Speicherobjekt angezeigt werden. In jedem der Counter-Diagramme werden die Gesamtwerte angezeigt, die in Lese-, Schreib- und andere Kategorien unterteilt sind. Darüber hinaus zeigen einige Counter-Diagramme zusätzliche Details an, wenn das Diagramm in der Zoom-Ansicht angezeigt wird.

In der folgenden Tabelle sind die verfügbaren Performance-Zählerdiagramme aufgeführt.

|===
| Verfügbare Diagramme | Diagrammbeschreibung 


 a| 
Veranstaltungen
 a| 
Zeigt kritische, Fehler-, Warn- und Informationsereignisse an, die mit den statistischen Diagrammen für das Root-Objekt korreliert sind. Zusätzlich zu den Performance-Ereignissen werden Systemzustandsereignisse angezeigt, um einen vollständigen Überblick über die Gründe zu geben, warum die Performance beeinträchtigt werden könnte.



 a| 
Latenz Insgesamt
 a| 
Anzahl der Millisekunden, die erforderlich sind, um auf Applikationsanforderungen zu reagieren. Beachten Sie, dass die durchschnittlichen Latenzwerte I/O-gewichtet sind.



 a| 
Latenz - Aufschlüsselung
 a| 
Dieselben Informationen, die in der Latenzzeit gesamt angezeigt werden, jedoch mit getrennten Performance-Daten in Lese-, Schreib- und sonstige Latenz.die Diagrammoption gilt nur, wenn das ausgewählte Objekt eine SVM, einen Node, ein Aggregat, ein Volume, eine LUN ist. Oder Namespace.



 a| 
Latenz – Cluster-Komponenten
 a| 
Dieselben Informationen, die in Latenz-Summe angezeigt werden, jedoch mit den Performance-Daten getrennt nach Cluster-Komponente in Latenz.Diese Diagrammoption gilt nur, wenn das ausgewählte Objekt ein Volume ist.



 a| 
IOPS – gesamt
 a| 
Anzahl der pro Sekunde verarbeiteten ein-/Ausgabevorgänge.



 a| 
IOPS – Aufschlüsselung
 a| 
Die gleichen Informationen, die auf dem IOPS-Wert insgesamt angezeigt werden, jedoch mit getrennten Performance-Daten in Lese-, Schreib- und sonstige IOPS. Bei Anzeige in der Zoom-Ansicht zeigt das Diagramm Volumes die minimalen und maximalen Durchsatzwerte der QoS an, sofern diese in ONTAP konfiguriert sind.

Diese Diagrammoption wird nur angewendet, wenn das ausgewählte Objekt eine SVM, einen Node, ein Aggregat, ein Volume, eine LUN, Oder Namespace.



 a| 
IOPS – Protokolle
 a| 
Die gleichen Informationen, die unter IOPS insgesamt angezeigt werden, aber die Performance-Daten werden in individuelle Diagramme für den Datenverkehr mit CIFS-, NFS-, FCP-, NVMe- und iSCSI-Protokollen unterteilt. Diese Diagrammoption wird nur angewendet, wenn das ausgewählte Objekt eine SVM ist.



 a| 
IOPS/TB – gesamt
 a| 
Anzahl der pro Sekunde verarbeiteten ein-/Ausgabevorgänge, basierend auf dem gesamten Speicherplatz, der vom Workload in Terabyte verbraucht wird. Dieser Zähler, auch I/O-Dichte genannt, misst die Performance mit einer bestimmten Menge an Storage-Kapazität.bei Anzeige in der Zoom-Ansicht zeigt das Diagramm Volumes QoS erwartet und Spitzendurchsatzwerte an, falls es in ONTAP konfiguriert ist.

Diese Diagrammoption gilt nur, wenn das ausgewählte Objekt ein Volume ist.



 a| 
MB/s – Gesamt
 a| 
Anzahl der Megabyte an Daten, die in das Objekt und vom Objekt pro Sekunde übertragen werden.



 a| 
Mbps - Aufschlüsselung
 a| 
Dieselben Informationen, die im Diagramm MB/s angezeigt werden, jedoch mit Trennung der MB/s-Daten in Festplattenlesevorgänge, Flash Cache Lese-, Schreib- und andere MB/s.bei Anzeige in der Ansicht Zoom zeigt das Volume-Diagramm QoS-Maximaldurchsatz an, sofern es in ONTAP konfiguriert ist.

Diese Diagrammoption wird nur angewendet, wenn das ausgewählte Objekt eine SVM, einen Node, ein Aggregat, ein Volume, eine LUN, Oder Namespace.

[NOTE]
====
Flash Cache-Daten werden nur für Nodes und nur angezeigt, wenn ein Flash Cache Modul im Node installiert ist.

====


 a| 
Genutzte Performance-Kapazität – Insgesamt
 a| 
Prozentsatz der Performance-Kapazität, die vom Node oder Aggregat verbraucht wird

[NOTE]
====
Daten zur Performance-Kapazität sind nur verfügbar, wenn die Nodes in einem Cluster mit der Software ONTAP 9.0 oder höher installiert sind.

====


 a| 
Genutzte Performance-Kapazität – Aufschlüsselung
 a| 
Die verwendete Performance-Kapazität ist in Benutzerprotokolle und Systembackground-Prozesse unterteilt. Darüber hinaus wird die Menge der freien Performance-Kapazität dargestellt.



 a| 
Verfügbare IOPS – gesamt
 a| 
Anzahl der ein-/Ausgabevorgänge pro Sekunde, die derzeit für dieses Objekt verfügbar sind (frei). Diese Zahl ergibt sich aus der Subtraktion der derzeit verwendeten IOPS von den IOPS-Gesamtwerten, die Unified Manager berechnet, die das Objekt ausführen kann. Diese Diagrammoption wird nur angewendet, wenn das ausgewählte Objekt ein Knoten oder Aggregat ist.

[NOTE]
====
Verfügbare IOPS-Daten sind nur verfügbar, wenn die Nodes in einem Cluster mit der Software ONTAP 9.0 oder höher installiert sind.

====


 a| 
Auslastung – Gesamt
 a| 
Verfügbarer Prozentsatz der verfügbaren Ressource des Objekts, das verwendet wird. Die Auslastung zeigt Node-Auslastung für Nodes, Festplattenauslastung für Aggregate und die Bandbreitenauslastung für Ports an. Diese Diagrammoption gilt nur, wenn es sich um ein Node, Aggregat oder Port handelt.



 a| 
Cache-Miss-Verhältnis - Gesamt
 a| 
Prozentsatz von Leseanforderungen von Client-Applikationen, die von der Festplatte zurückgegeben werden, anstatt vom Cache zurückgegeben zu werden. Diese Diagrammoption gilt nur, wenn das ausgewählte Objekt ein Volume ist.

|===