---
permalink: online-help/task-moving-workloads-to-a-different-node.html 
sidebar: sidebar 
keywords:  
summary: Mithilfe von Unified Manager können Sie ein Aggregat auf einem anderen Node identifizieren, der weniger ausgelastet ist als der Node, auf dem Ihre Workloads derzeit ausgeführt werden. Anschließend können Sie ausgewählte Volumes zu diesem Aggregat verschieben. Durch die Migration hochperformanter Workloads auf ein Aggregat auf einem weniger ausgelasteten Node können die Workloads auf beiden Nodes effizienter ausgeführt werden. 
---
= Workloads werden auf einen anderen Node verschoben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mithilfe von Unified Manager können Sie ein Aggregat auf einem anderen Node identifizieren, der weniger ausgelastet ist als der Node, auf dem Ihre Workloads derzeit ausgeführt werden. Anschließend können Sie ausgewählte Volumes zu diesem Aggregat verschieben. Durch die Migration hochperformanter Workloads auf ein Aggregat auf einem weniger ausgelasteten Node können die Workloads auf beiden Nodes effizienter ausgeführt werden.



== Bevor Sie beginnen

* Sie müssen über die Rolle „Operator“, „OnCommand Administrator“ oder „Storage Administrator“ verfügen.
* Sie müssen den Namen des Node notiert haben, der derzeit ein Performance-Problem hat.
* Sie müssen das Datum und die Uhrzeit aufgezeichnet haben, zu der der Node das Performance-Ereignis erhalten hat.
* Sie müssen die Ereignis-ID--zum Beispiel „`p-sdt-clus1-nod-6982`“ aufgezeichnet haben.
* Unified Manager muss Performance-Daten für einen Monat oder länger erfassen und analysieren haben.




== Über diese Aufgabe

Mithilfe dieses Verfahrens können Sie die folgenden Ressourcen ermitteln, um hochperformante Workloads auf einen weniger ausgelasteten Node zu verschieben:

* Die Nodes in demselben Cluster verfügen über die höchste freie Performance-Kapazität
* Die Aggregate auf dem neuen Node mit der höchsten freien Performance-Kapazität
* Die Volumes mit der höchsten Performance auf dem aktuellen Node




== Schritte

. Ermitteln Sie einen Node im Cluster mit der größten freien Performance-Kapazität:
+
.. Klicken Sie auf der Seite *Event Details* auf den Namen des Clusters, auf dem sich der Knoten befindet.
+
Die Cluster-Details werden auf der Landing Page Performance/Cluster angezeigt.

.. Klicken Sie auf der Registerkarte *Übersicht* im Bereich *verwaltete Objekte* auf *Knoten*.
+
Die Liste der Nodes auf diesem Cluster wird angezeigt.

.. Klicken Sie auf die Spalte *verwendete Performance-Kapazität*, um die Knoten nach dem geringsten Prozentsatz zu sortieren.
+
Diese enthält eine Liste potenzieller Nodes, zu die Sie Workloads verschieben können.

.. Notieren Sie sich den Namen des Node, auf den Sie die Workloads verschieben möchten.


. Identifizieren Sie ein Aggregat auf dem neuen Node, der am wenigsten genutzt wird:
+
.. Klicken Sie im linken Navigationsbereich auf *Leistung* > *Aggregate*.
+
Die Seite Performance/Aggregate wird angezeigt.

.. Klicken Sie im linken Dropdown-Menü auf *Filterung*, wählen Sie *Knoten* aus, geben Sie den Namen des Knotens in das Textfeld ein und klicken Sie dann auf *Filter anwenden*.
+
Die Seite Performance/Aggregate wird mit der Liste der auf diesem Node verfügbaren Aggregate neu angezeigt.

.. Klicken Sie auf die Spalte *Performance Capacity Used*, um die Aggregate nach den am wenigsten verwendeten Aggregaten zu sortieren.
+
Diese Liste enthält potenzielle Aggregate, zu denen Workloads verschoben werden können.

.. Notieren Sie sich den Namen des Aggregats, zu dem Sie die Workloads verschieben möchten.


. Ermitteln Sie die hochperformanten Workloads vom Node, der das Ereignis erhalten hat:
+
.. Kehren Sie zur Seite *Veranstaltungsdetails* für die Veranstaltung zurück.
.. Klicken Sie im Feld *Betroffene Volumes* auf den Link für die Anzahl der Volumes.
+
Die Seite Performance/Volumes wird mit einer gefilterten Liste der Volumes auf diesem Node angezeigt.

.. Klicken Sie auf die Spalte *Gesamtkapazität*, um die Volumes nach dem größten zugewiesenen Speicherplatz zu sortieren.
+
Hier wird eine Liste potenzieller Volumes angezeigt, die Sie möglicherweise verschieben möchten.

.. Notieren Sie sich die Namen der Volumes, die Sie verschieben möchten, sowie die Namen der aktuellen Aggregate, auf denen sich diese befinden.


. Verschieben Sie die Volumes zu den Aggregaten, die Sie als größte freie Performance-Kapazität auf dem neuen Node identifiziert haben.
+
Sie können die Schritte für die Verschiebung mit OnCommand System Manager, OnCommand Workflow Automation, ONTAP Befehlen oder einer Kombination dieser Tools ausführen.





== Nachdem Sie fertig sind

Nach einigen Tagen können Sie überprüfen, ob Sie von diesem Node bzw. Aggregat dieselbe Art von Ereignissen erhalten.
