---
permalink: online-help/task-viewing-the-list-of-snapshot-copies.html 
sidebar: sidebar 
keywords:  
summary: Sie können die Liste der Snapshot Kopien für ein ausgewähltes Volume anzeigen. Mithilfe der Liste der Snapshot Kopien lässt sich die Menge an Festplattenspeicher berechnen, die zurückgewonnen werden kann, wenn eine oder mehrere Snapshot Kopien gelöscht werden. Außerdem können Sie die Snapshot Kopien bei Bedarf löschen. 
---
= Anzeigen der Liste der Snapshot Kopien
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Liste der Snapshot Kopien für ein ausgewähltes Volume anzeigen. Mithilfe der Liste der Snapshot Kopien lässt sich die Menge an Festplattenspeicher berechnen, die zurückgewonnen werden kann, wenn eine oder mehrere Snapshot Kopien gelöscht werden. Außerdem können Sie die Snapshot Kopien bei Bedarf löschen.



== Bevor Sie beginnen

* Sie müssen über die Rolle „Operator“, „OnCommand Administrator“ oder „Storage Administrator“ verfügen.
* Das Volume, das die Snapshot Kopien enthält, muss online sein.




== Schritte

. Klicken Sie im linken Navigationsbereich auf *Systemzustand* > *Volumes*.
. Wählen Sie auf der Seite *Systemzustand/Volumes* Inventar das Volume aus, das die Snapshot Kopien enthält, die Sie anzeigen möchten.
. Klicken Sie auf der Seite *Health/Volume* Details auf die Registerkarte *Capacity*.
. Klicken Sie im Fensterbereich *Details* der Registerkarte *Kapazität* im Abschnitt Weitere Details auf den Link neben *Snapshot Kopien*.
+
Die Anzahl der Snapshot Kopien ist ein Link, der die Liste der Snapshot Kopien anzeigt.


