---
permalink: online-help/task-quiescing-a-protection-relationship-from-the-volume-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite „Schutz/Volume-Beziehungen“ können Sie eine Schutzbeziehung stilllegen, um vorübergehend Datenübertragungen zu verhindern. Sie könnten eine Beziehung stilllegen, wenn Sie eine Snapshot Kopie eines SnapMirror Ziel-Volumes erstellen möchten, das eine Datenbank enthält, und Sie wollen sicherstellen, dass der Inhalt während des Snapshot Kopiervorgangs stabil ist. 
---
= Eine Schutzbeziehung wird auf der Seite „Schutz/Volume-Beziehungen“ stillgelegt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Schutz/Volume-Beziehungen“ können Sie eine Schutzbeziehung stilllegen, um vorübergehend Datenübertragungen zu verhindern. Sie könnten eine Beziehung stilllegen, wenn Sie eine Snapshot Kopie eines SnapMirror Ziel-Volumes erstellen möchten, das eine Datenbank enthält, und Sie wollen sicherstellen, dass der Inhalt während des Snapshot Kopiervorgangs stabil ist.



== Bevor Sie beginnen

* Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.




== Über diese Aufgabe

Die Aktion quiesce wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung vorhanden ist und der Ziel-Cluster noch nicht erkannt wurde
* Wenn Workflow Automation und Unified Manager noch nicht in Kombination Paar liegen




== Schritte

. Um Transfers für eine oder mehrere Schutzbeziehungen stillzulegen, wählen Sie auf der Seite *Schutz/Volume-Beziehungen* ein oder mehrere Volumes aus und klicken Sie in der Symbolleiste auf *Quiesce*.
+
Das Dialogfeld Quiesce wird angezeigt.

. Klicken Sie Auf *Weiter*.
+
Der Status des Jobs quiesce wird oben auf der Seite Health/Volume Details angezeigt, zusammen mit einem Link zu den Jobdetails.

. Klicken Sie auf den Link *Details anzeigen*, um zur Detailseite *Schutz/Job* weitere Details und den Job-Fortschritt aufzurufen.
. Klicken Sie auf den Pfeil *Zurück* in Ihrem Browser, um zur Seite *Schutz/Volume-Beziehungen* zurückzukehren.
+
Der quiesce-Job ist abgeschlossen, wenn alle Arbeitsaufgaben erfolgreich abgeschlossen wurden.


