---
permalink: online-help/task-changing-the-local-user-password.html 
sidebar: sidebar 
keywords:  
summary: Sie können Ihr lokales Benutzeranmeldeswort ändern, um potenzielle Sicherheitsrisiken zu vermeiden. 
---
= Ändern des lokalen Benutzerpassworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihr lokales Benutzeranmeldeswort ändern, um potenzielle Sicherheitsrisiken zu vermeiden.



== Bevor Sie beginnen

Sie müssen als lokaler Benutzer angemeldet sein.



== Über diese Aufgabe

Die Passwörter für den Wartungsbenutzer und für Remote-Benutzer können mit diesen Schritten nicht geändert werden. Wenden Sie sich an Ihren Passwortadministrator, um ein Kennwort für Remote-Benutzer zu ändern. Informationen zum Ändern des Wartungs-Benutzerpassworts finden Sie unter link:../health-checker/task-using-the-maintenance-console.html["Verwenden der Wartungskonsole"].



== Schritte

. Melden Sie sich bei Unified Manager an.
. Klicken Sie in der oberen Menüleiste auf das Benutzersymbol und dann auf *Passwort ändern*.
+
Die Option *Passwort ändern* wird nicht angezeigt, wenn Sie ein Remote-Benutzer sind.

. Geben Sie im Dialogfeld *Passwort ändern* das aktuelle Passwort und das neue Passwort ein.
. Klicken Sie Auf *Speichern*.




== Nachdem Sie fertig sind

Wenn Unified Manager in einer Hochverfügbarkeitskonfiguration konfiguriert ist, müssen Sie das Passwort auf dem zweiten Node des Setup ändern. Beide Instanzen müssen dasselbe Passwort haben.
