---
permalink: online-help/task-previewing-changes-to-your-data-policy.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten alle Änderungen an Ihren Regeln in einer Datenrichtlinie in einer Vorschau anzeigen, bevor Sie die Änderungen in der Datenrichtlinie mit Infinite Volume zur Aktivierung an der SVM übermitteln. 
---
= Anzeigen von Änderungen an Ihrer Datenrichtlinie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten alle Änderungen an Ihren Regeln in einer Datenrichtlinie in einer Vorschau anzeigen, bevor Sie die Änderungen in der Datenrichtlinie mit Infinite Volume zur Aktivierung an der SVM übermitteln.



== Bevor Sie beginnen

Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Die Registerkarte Datenrichtlinie ist nur für eine SVM mit Infinite Volume sichtbar.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Systemzustand* > *SVMs*.
. Wählen Sie auf der Seite *Health/Storage Virtual Machines* Inventory die entsprechende SVM aus.
. Klicken Sie Auf *Datenrichtlinie*.
+
Es wird eine Liste der Regeln in der Datenrichtlinie für die ausgewählte SVM mit Infinite Volume angezeigt.

. Ändern Sie die Datenrichtlinie nach Bedarf.
+
Änderungen an Datenrichtlinien können das Erstellen neuer Regeln, das Bearbeiten vorhandener Regeln, das Löschen vorhandener Regeln oder das Neuanordnen der Regeln umfassen.

. Klicken Sie Auf *Aktivieren*.
. Im Fenster *Summary of Changes to Data Policy Configuration* können Sie die Änderungen an Ihrer Datenrichtlinie in der Vorschau anzeigen und dann auf *Activate* klicken, um die Änderungen der Datenrichtlinie in der SVM mit Infinite Volume zu aktivieren.

