---
permalink: online-help/task-adding-space-to-the-data-directory-of-the-unified-manager-red-hat-enterprise-linux-host.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie dem Verzeichnis /opt/netapp/Data nicht genügend Speicherplatz zugewiesen haben, um Unified Manager zu unterstützen, wenn Sie den Linux-Host ursprünglich eingerichtet und dann Unified Manager installiert haben, können Sie nach der Installation Speicherplatz hinzufügen, indem Sie den Speicherplatz im Verzeichnis /opt/netapp/Data vergrößern. 
---
= Hinzufügen von Speicherplatz zum Datenverzeichnis des Linux-Hosts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie dem nicht genügend Speicherplatz zugewiesen haben `/opt/netapp/data` Verzeichnis zur Unterstützung von Unified Manager Wenn Sie ursprünglich den Linux-Host eingerichtet und dann Unified Manager installiert haben, können Sie nach der Installation Speicherplatz hinzufügen, indem Sie den Speicherplatz auf dem erhöhen `/opt/netapp/data` Verzeichnis.



== Bevor Sie beginnen

Sie müssen Root-Benutzerzugriff auf die Red hat Enterprise Linux oder CentOS Linux Maschine haben, auf der Unified Manager installiert ist.



== Über diese Aufgabe

Wir empfehlen, dass Sie ein Backup der Unified Manager-Datenbank erstellen, bevor Sie die Größe des Datenverzeichnisses vergrößern.



== Schritte

. Melden Sie sich als Root-Benutzer an dem Linux-Rechner an, auf dem Sie Speicherplatz hinzufügen möchten.
. Beenden Sie den Unified Manager-Service und die zugehörige MySQL-Software in der folgenden Reihenfolge:
. Erstellen eines temporären Sicherungsordners (z. B. `/backup-data`) Mit genügend Speicherplatz, um die Daten im aktuellen zu enthalten `/opt/netapp/data` Verzeichnis.
. Kopieren Sie den Inhalt und die Berechtigungskonfiguration des vorhandenen `/opt/netapp/data` Verzeichnis zum Verzeichnis der Sicherungsdaten: `cp -rp /opt/netapp/data/* /backup-data`
. Wenn SE Linux aktiviert ist:
+
.. Holen Sie sich den SE Linux-Typ für Ordner auf bestehenden `/opt/netapp/data` Ordner:
+
`se_type= ls -Z /opt/netapp/data | awk '{print $4}'| awk -F: '{print $3}'| head -1`

+
Das System gibt eine Bestätigung wie die folgende aus:

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. Führen Sie die aus `chcon` Befehl zum Festlegen des SE Linux-Typs für das Backup-Verzeichnis: `chcon -R --type=mysqld_db_t /backup-data`


. Entfernen Sie den Inhalt des `/opt/netapp/data` Verzeichnis:
+
.. `cd /opt/netapp/data`
.. `rm -rf *`


. Erweitern Sie die Größe des `/opt/netapp/data` Verzeichnis auf mindestens 750 GB über LVM-Befehle oder durch Hinzufügen zusätzlicher Festplatten.
+
[NOTE]
====
Montieren des `/opt/netapp/data` Das Verzeichnis in einem NFS-Export oder einer CIFS-Freigabe wird nicht unterstützt.

====
. Bestätigen Sie das `/opt/netapp/data` Verzeichnis-Inhaber (mysql) und Gruppe (root) bleiben unverändert: `ls -ltr / | grep opt/netapp/data`
+
Das System gibt eine Bestätigung wie die folgende aus:

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. Wenn SE Linux aktiviert ist, bestätigen Sie den Kontext für das `/opt/netapp/data` Verzeichnis ist noch auf mysqld_db_t eingestellt: `touch /opt/netapp/data/abc``ls -Z /opt/netapp/data/abc`
+
Das System gibt eine Bestätigung wie die folgende aus:

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----
. Kopieren Sie den Inhalt von `backup-data`, Zurück zu den erweiterten `/opt/netapp/data` Verzeichnis: `cp -rp /backup-data/* /opt/netapp/data/`
. Starten Sie den MySQL-Dienst: `service mysqld start`
. Nachdem der MySQL-Dienst gestartet wurde, starten sie die ocie- und ocieau-Dienste in der folgenden Reihenfolge: `service ocie start``service ocieau start`
. Löschen Sie nach dem Start aller Dienste den Sicherungsordner `/backup-data`: `rm -rf /backup-data`

