---
permalink: online-help/task-editing-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Sie können vorhandene Schutzbeziehungen bearbeiten, um die aktuelle maximale Übertragungsrate, Schutzrichtlinie oder den Schutzzeitplan zu ändern. Sie können eine Beziehung bearbeiten, um die für Datentransfers verwendete Bandbreite zu verringern oder die Häufigkeit geplanter Transfers zu erhöhen, da sich Daten oft ändern. 
---
= Bearbeiten von Schutzbeziehungen auf der Seite „Angaben zum Zustand/Volumen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können vorhandene Schutzbeziehungen bearbeiten, um die aktuelle maximale Übertragungsrate, Schutzrichtlinie oder den Schutzzeitplan zu ändern. Sie können eine Beziehung bearbeiten, um die für Datentransfers verwendete Bandbreite zu verringern oder die Häufigkeit geplanter Transfers zu erhöhen, da sich Daten oft ändern.



== Bevor Sie beginnen

* Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.
* Workflow Automation muss installiert und konfiguriert sein.




== Über diese Aufgabe

Die ausgewählten Volumes müssen Schutzbeziehungsziele sein. Sie können Beziehungen nicht bearbeiten, wenn Quell-Volumes, Volumes für die Lastverteilung oder Volumes ausgewählt werden, die nicht Ziel einer SnapMirror oder SnapVault Beziehung sind.



== Schritte

. Suchen Sie auf der Seite *Schutz* der *Gesundheit/Volumen*-Details in der Topologie die Schutzbeziehung, die Sie bearbeiten möchten, und klicken Sie mit der rechten Maustaste darauf.
. Wählen Sie im Menü * Bearbeiten* aus.
+
Alternativ können Sie im Menü *Aktionen* die Option *Beziehung* > *Bearbeiten* wählen, um die Beziehung zu bearbeiten, für die Sie die Details anzeigen.

+
Das Dialogfeld Beziehung bearbeiten wird angezeigt.

. Bearbeiten Sie im Dialogfeld „Beziehungen bearbeiten*“ die maximale Übertragungsrate, die Schutzrichtlinie oder den Schutzzeitplan nach Bedarf.
. Klicken Sie Auf *Anwenden*.
+
Die Änderungen werden auf die ausgewählten Beziehungen angewendet.


