---
permalink: online-help/task-viewing-user-and-user-group-quotas.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite Health/Storage Virtual Machines Inventory werden Informationen über die auf der SVM konfigurierten Benutzer- und Benutzergruppenkontingente angezeigt. Sie können den Namen des Benutzers oder der Benutzergruppe, die auf Festplatten und Dateien festgelegten Grenzen, den verwendeten Festplatten- und Dateispeicherplatz und die E-Mail-Adresse für Benachrichtigungen anzeigen. 
---
= Anzeigen von Benutzer- und Benutzergruppenkontingenten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Health/Storage Virtual Machines Inventory werden Informationen über die auf der SVM konfigurierten Benutzer- und Benutzergruppenkontingente angezeigt. Sie können den Namen des Benutzers oder der Benutzergruppe, die auf Festplatten und Dateien festgelegten Grenzen, den verwendeten Festplatten- und Dateispeicherplatz und die E-Mail-Adresse für Benachrichtigungen anzeigen.



== Bevor Sie beginnen

Sie müssen eine der folgenden Rollen haben, um diese Aufgabe auszuführen: Operator, OnCommand Administrator oder Storage Administrator.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Systemzustand* > *SVMs*.
. Wählen Sie auf der Seite *Health/Storage Virtual Machines* Inventory eine SVM aus und klicken Sie dann auf die Registerkarte *Benutzer- und Gruppenkontingente*.

