---
permalink: online-help/task-editing-resource-pools.html 
sidebar: sidebar 
keywords:  
summary: Sie können einen vorhandenen Ressourcenpool bearbeiten, wenn Sie den Namen des Ressourcenpool und die Beschreibung ändern möchten. 
---
= Bearbeiten von Ressourcenpools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen vorhandenen Ressourcenpool bearbeiten, wenn Sie den Namen des Ressourcenpool und die Beschreibung ändern möchten.



== Bevor Sie beginnen

Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Die Schaltfläche *Bearbeiten* ist nur aktiviert, wenn ein Ressourcenpool ausgewählt ist. Wenn mehrere Ressourcen-Pools ausgewählt sind, ist die Schaltfläche *Bearbeiten* deaktiviert.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Schutz* > *Ressourcen-Pools*.
. Wählen Sie einen Ressourcenpool aus der Liste aus.
. Klicken Sie Auf *Bearbeiten*.
+
Das Fenster „Ressourcen-Pool bearbeiten“ wird angezeigt.

. Bearbeiten Sie den Namen und die Beschreibung des Ressourcenpool nach Bedarf.
. Klicken Sie Auf *Speichern*.
+
Der neue Name und eine neue Beschreibung werden in der Liste Ressourcen-Pool angezeigt.


