---
permalink: online-help/task-viewing-the-node-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite „Systemzustand/Knoten-Inventar“ können Sie die Liste der Knoten in Ihren Clustern anzeigen. Auf der Seite „Systemzustand/Cluster-Details“ können Sie detaillierte Informationen zu Nodes anzeigen, die Teil des überwachten Clusters sind. 
---
= Anzeigen der Node-Liste und der Details
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Systemzustand/Knoten-Inventar“ können Sie die Liste der Knoten in Ihren Clustern anzeigen. Auf der Seite „Systemzustand/Cluster-Details“ können Sie detaillierte Informationen zu Nodes anzeigen, die Teil des überwachten Clusters sind.



== Bevor Sie beginnen

Sie müssen über die Rolle „Operator“, „OnCommand Administrator“ oder „Storage Administrator“ verfügen.



== Über diese Aufgabe

Sie können Details wie den Node-Status, den Cluster mit dem Node, die zusammengefasste Kapazität (verwendet und insgesamt) und Details zur Rohkapazität (nutzbar, frei und insgesamt) anzeigen. Zudem erhalten Sie Informationen über HA-Paare, Festplatten-Shelfs und Ports.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Gesundheit* > *Knoten*.
. Klicken Sie auf der Seite *Health/Nodes* Inventory auf den Knoten, dessen Details Sie anzeigen möchten.
+
Die detaillierten Informationen für den ausgewählten Node werden auf der Seite „Systemzustand/Cluster-Details“ angezeigt. Im linken Teilfenster wird die Liste der HA-Paare angezeigt. Standardmäßig sind die HA-Details geöffnet, in denen Details zum HA-Status und Ereignisse im Zusammenhang mit dem ausgewählten HA-Paar angezeigt werden.

. Um weitere Details zum Knoten anzuzeigen, führen Sie die entsprechende Aktion aus:
+
|===
| Anzeigen... | Klicken Sie Auf... 


 a| 
Informationen zu Platten-Shelves
 a| 
*Platten-Shelves*.



 a| 
Port-bezogene Informationen
 a| 
*Ports*.

|===

