---
permalink: online-help/task-deleting-resource-pools.html 
sidebar: sidebar 
keywords:  
summary: Sie können Ressourcenpools löschen, wenn sie nicht mehr benötigt werden. Beispielsweise möchten Sie die Mitgliedslegierung von einem Ressourcenpool auf mehrere andere Ressourcenpools verteilen, sodass der ursprüngliche Ressourcenpool überflüssig wird. 
---
= Löschen von Ressourcenpools
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ressourcenpools löschen, wenn sie nicht mehr benötigt werden. Beispielsweise möchten Sie die Mitgliedslegierung von einem Ressourcenpool auf mehrere andere Ressourcenpools verteilen, sodass der ursprüngliche Ressourcenpool überflüssig wird.



== Bevor Sie beginnen

Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Die Schaltfläche *Löschen* ist nur aktiviert, wenn mindestens ein Ressourcen-Pool ausgewählt ist.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Schutz* > *Ressourcen-Pools*.
. Wählen Sie den Ressourcenpool aus, den Sie löschen möchten.
. Klicken Sie Auf *Löschen*.
+
Der Ressourcen-Pool wird aus der Ressourcen-Pool-Liste entfernt und seine Aggregate werden aus der Mitgliederliste entfernt.


