---
permalink: online-help/task-editing-alerts.html 
sidebar: sidebar 
keywords:  
summary: Sie können Eigenschaften von Warnmeldungen bearbeiten, z. B. die Ressource, mit der die Warnmeldung verknüpft ist, Ereignisse, Empfänger, Benachrichtigungsoptionen, Benachrichtigungshäufigkeit, Und zugehörigen Skripts. 
---
= Bearbeiten von Warnungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Eigenschaften von Warnmeldungen bearbeiten, z. B. die Ressource, mit der die Warnmeldung verknüpft ist, Ereignisse, Empfänger, Benachrichtigungsoptionen, Benachrichtigungshäufigkeit, Und zugehörigen Skripts.



== Bevor Sie beginnen

Sie müssen die OnCommand-Administratorrolle besitzen.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Konfiguration* > *Alerting*.
. Wählen Sie auf der Seite *Konfiguration/Alerting* den zu bearbeitenden Alarm aus, und klicken Sie auf *Bearbeiten*.
. Bearbeiten Sie im Dialogfeld *Alarm bearbeiten* den Namen, die Ressourcen, Ereignisse und Aktionen. Nach Bedarf.
+
Sie können das Skript, das der Warnung zugeordnet ist, ändern oder entfernen.

. Klicken Sie Auf *Speichern*.

