---
permalink: online-help/task-identifying-victim-workloads-involved-in-a-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 'In Unified Manager können Sie ermitteln, welche Volume-Workloads die höchste Abweichung der Reaktionszeit von \(Latenz\) aufweisen, die durch eine Storage-Komponente verursacht wurde. Anhand der Identifizierung dieser Workloads können Sie nachvollziehen, warum die Client-Applikationen, auf die sie zugreifen, langsamer als normal ausgeführt wurden.' 
---
= Identifizierung der Opfer-Workloads, die an einem dynamischen Performance-Ereignis beteiligt sind
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager können Sie ermitteln, welche Volume Workloads die höchste Abweichung der Reaktionszeit (Latenz) aufweisen, die durch eine Storage-Komponente verursacht wurde. Anhand der Identifizierung dieser Workloads können Sie nachvollziehen, warum die Client-Applikationen, auf die sie zugreifen, langsamer als normal ausgeführt wurden.



== Bevor Sie beginnen

* Sie müssen über die Rolle „Operator“, „OnCommand Administrator“ oder „Storage Administrator“ verfügen.
* Es müssen neue, anerkannte oder veraltete dynamische Leistungsereignisse vorliegen.




== Über diese Aufgabe

Auf der Seite Ereignisdetails wird eine Liste der benutzerdefinierten und systemdefinierten Workloads angezeigt, die nach der höchsten Abweichung von Aktivität oder Auslastung der Komponente oder am stärksten vom Ereignis betroffen sind. Die Werte basieren auf den Peaks, die Unified Manager bei der Erkennung und letzten Analyse des Ereignisses ermittelt hat.



== Schritte

. Rufen Sie die Seite *Ereignisdetails* auf, um Informationen über das Ereignis anzuzeigen.
. Wählen Sie in den Diagrammen Workload-Latenz und Workload-Aktivität *Opfer-Workloads* aus.
. Bewegen Sie den Mauszeiger über die Diagramme, um die obersten benutzerdefinierten Workloads anzuzeigen, die sich auf die Komponente auswirken, und den Namen des Workloads mit dem Opfer anzuzeigen.

