---
permalink: online-help/task-removing-a-protection-relationship.html 
sidebar: sidebar 
keywords:  
summary: 'Auf der Seite „Schutz/Volume-Beziehungen“ können Sie eine Schutzbeziehung entfernen, um eine bestehende Beziehung zwischen der ausgewählten Quelle und dem ausgewählten Ziel dauerhaft zu löschen: Zum Beispiel, wenn Sie eine Beziehung unter Verwendung eines anderen Ziels erstellen möchten. Durch diesen Vorgang werden alle Metadaten entfernt und können nicht rückgängig gemacht werden.' 
---
= Entfernen einer Schutzbeziehung von der Seite „Schutz/Volume-Beziehungen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Schutz/Volume-Beziehungen“ können Sie eine Schutzbeziehung entfernen, um eine bestehende Beziehung zwischen der ausgewählten Quelle und dem ausgewählten Ziel dauerhaft zu löschen: Zum Beispiel, wenn Sie eine Beziehung unter Verwendung eines anderen Ziels erstellen möchten. Durch diesen Vorgang werden alle Metadaten entfernt und können nicht rückgängig gemacht werden.



== Bevor Sie beginnen

* Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.




== Schritte

. Wählen Sie auf der Seite *Schutz/Volume-Beziehungen* ein oder mehrere Volumes mit Schutzbeziehungen aus, die Sie entfernen möchten, und klicken Sie in der Symbolleiste auf *Entfernen*.
+
Das Dialogfeld Beziehung entfernen wird angezeigt.

. Klicken Sie auf *Weiter*, um die Beziehung zu entfernen.
+
Die Beziehung wird von der Seite „Schutz/Volume-Beziehungen“ entfernt.


