---
permalink: online-help/task-creating-a-snapvault-protection-relationship-from-the-health-volumes-page.html 
sidebar: sidebar 
keywords:  
summary: 'Sie können die Seite „Systemzustand“/„Volumes-Bestandsaufnahme“ verwenden, um SnapVault-Beziehungen für ein oder mehrere Volumes auf derselben Storage Virtual Machine \ (SVM\) zu erstellen, um Daten-Backups zu Sicherungszwecken zu ermöglichen.' 
---
= Erstellen einer SnapVault-Schutzbeziehung über die Seite „Systemzustand/Volumen-Inventar“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Systemzustand“/„Volumes-Bestandsaufnahme“ können Sie SnapVault-Beziehungen für ein oder mehrere Volumes auf derselben Storage Virtual Machine (SVM) erstellen, um Daten-Backups zu Sicherungszwecken zu ermöglichen.



== Bevor Sie beginnen

Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Das Menü * Protect* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung vorhanden ist und der Ziel-Cluster noch nicht erkannt wurde




== Schritte

. Klicken Sie im linken Navigationsbereich auf *Systemzustand* > *Volumes*.
. Klicken Sie auf der Seite *Health/Volumes* Inventory mit der rechten Maustaste auf ein Volume, das Sie schützen möchten, und wählen Sie *Protect* aus.
+
Wenn Sie mehrere Sicherungsbeziehungen auf derselben virtuellen Speichermaschine (SVM) erstellen möchten, wählen Sie auf der Seite Health/Volumes Inventory ein oder mehrere Volumes aus, und klicken Sie in der Symbolleiste auf *Protect*.

. Wählen Sie im Menü * SnapVault* aus.
+
Das Dialogfeld Schutz konfigurieren wird gestartet.

. Klicken Sie auf *SnapVault*, um die Registerkarte *SnapVault* anzuzeigen und die Informationen zum sekundären Volume zu konfigurieren.
. Klicken Sie auf *Erweitert*, um Deduplizierung, Komprimierung, Autogrow und Platzgarantie nach Bedarf festzulegen und klicken Sie dann auf *Apply*.
. Füllen Sie auf der Registerkarte *SnapVault* den Bereich *Zielinformationen* und den Bereich *Beziehungseinstellungen* aus.
. Klicken Sie Auf *Anwenden*.
+
Sie gelangen wieder zur Seite „Health/Volumes Inventory“.

. Klicken Sie oben auf der Seite *Health/Volumes* Inventory auf den Link für die Schutzkonfiguration.
+
Wenn Sie nur eine Schutzbeziehung erstellen, wird die Seite Schutz-/Jobdetails angezeigt. Wenn Sie jedoch mehr als eine Schutzbeziehung erstellen, wird eine gefilterte Liste aller Jobs angezeigt, die mit dem Schutzvorgang verknüpft sind.

. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie nur einen Job haben, klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
** Wenn Sie mehr als einen Job haben:
+
... Klicken Sie in der Liste Jobs auf einen Job.
... Klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
... Verwenden Sie die Schaltfläche *Zurück*, um zur gefilterten Liste zurückzukehren und einen anderen Job anzuzeigen.





