---
permalink: online-help/task-aborting-an-active-data-protection-transfer.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine aktive Datensicherung abbrechen, wenn Sie eine SnapMirror Replikation anhalten möchten, die gerade ausgeführt wird. Sie können auch den Checkpoint beim Neustart für Transfers nach dem Basistransfer löschen. Sie können eine Übertragung abbrechen, wenn sie mit einem anderen Vorgang, z. B. einer Volume-Verschiebung, kollidieren. 
---
= Aktive Datensicherungstransfers wird auf der Seite „Protection/Volume Relationships“ abgebrochen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine aktive Datensicherung abbrechen, wenn Sie eine SnapMirror Replikation anhalten möchten, die gerade ausgeführt wird. Sie können auch den Checkpoint beim Neustart für Transfers nach dem Basistransfer löschen. Sie können eine Übertragung abbrechen, wenn sie mit einem anderen Vorgang, z. B. einer Volume-Verschiebung, kollidieren.



== Bevor Sie beginnen

* Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten.




== Über diese Aufgabe

Die Abbruchaktion wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung besteht und der Ziel-Cluster noch nicht erkannt wurde


Sie können den Kontrollpunkt für den Neustart für einen Basistransfer nicht löschen.



== Schritte

. Um Übertragungen für eine oder mehrere Schutzbeziehungen abzubrechen, wählen Sie auf der Seite *Schutz/Volume-Beziehungen* ein oder mehrere Volumes aus und klicken Sie in der Symbolleiste auf *Abbrechen*.
+
Das Dialogfeld Übertragung abbrechen wird angezeigt.

. Wenn Sie den Kontrollpunkt für den Neustart für einen Transfer löschen möchten, der kein Basistransfer ist, wählen Sie *Checkpoints löschen* aus.
. Klicken Sie Auf *Weiter*.
+
Das Dialogfeld Übertragung abbrechen wird geschlossen, und der Status des Jobs abbrechen wird oben auf der Seite Schutz-/Volume-Beziehungen angezeigt, zusammen mit einem Link zu den Jobdetails.

. Klicken Sie auf den Link *Details anzeigen*, um weitere Details zur Seite *Schutz/Job* anzuzeigen und den Job-Fortschritt anzuzeigen.

