---
permalink: online-help/task-editing-individual-volume-health-threshold-settings.html 
sidebar: sidebar 
keywords:  
summary: Sie können die Statusschwellenwerte für Volume-Kapazität, Wachstum, Kontingent und Speicherplatzreserve eines oder mehrerer Volumes bearbeiten. Wenn ein Schwellenwert überschritten wird, werden Warnungen erzeugt und Sie erhalten Benachrichtigungen. Diese Benachrichtigungen helfen Ihnen, auf Basis des generierten Ereignisses vorbeugende Maßnahmen zu ergreifen. 
---
= Bearbeiten von Schwellenwerten für den Zustand einzelner Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Statusschwellenwerte für Volume-Kapazität, Wachstum, Kontingent und Speicherplatzreserve eines oder mehrerer Volumes bearbeiten. Wenn ein Schwellenwert überschritten wird, werden Warnungen erzeugt und Sie erhalten Benachrichtigungen. Diese Benachrichtigungen helfen Ihnen, auf Basis des generierten Ereignisses vorbeugende Maßnahmen zu ergreifen.



== Bevor Sie beginnen

Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Basierend auf Änderungen an den Schwellenwerten werden Ereignisse im nächsten Überwachungszyklus generiert oder veraltet.

Beachten Sie, dass bei Aktivierung von Autogrow auf einem Volume die Kapazitätsschwellenwerte basierend auf der durch Autogrow festgelegten maximalen Volume-Größe gelten und nicht auf der ursprünglichen Volume-Größe basieren.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Systemzustand* > *Volumes*.
. Wählen Sie auf der Seite *Health/Volumes* Inventory ein oder mehrere Volumes aus und klicken Sie dann auf *Schwellenwerte bearbeiten*.
. Bearbeiten Sie im Dialogfeld *Volume Schwellenwerte bearbeiten* die Schwellenwerteinstellungen eines der folgenden Werte: Kapazität, Snapshot-Kopien, qtree-Kontingent, Wachstum oder Inodes, indem Sie das entsprechende Kontrollkästchen aktivieren und dann die Einstellungen ändern.
. Klicken Sie Auf *Speichern*.

