---
permalink: online-help/task-viewing-fabricpool-capacity-information.html 
sidebar: sidebar 
keywords:  
summary: Sie können FabricPool Kapazitätsinformationen für Cluster, Aggregate und Volumes auf den Seiten „Health Inventory“ und „Details“ für diese Objekte anzeigen. Sie können auch FabricPool-Informationen im Bericht über Aggregatskapazität und -Auslastung anzeigen. 
---
= Anzeigen von Informationen zur FabricPool-Kapazität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können FabricPool Kapazitätsinformationen für Cluster, Aggregate und Volumes auf den Seiten „Health Inventory“ und „Details“ für diese Objekte anzeigen. Sie können auch FabricPool-Informationen im Bericht über Aggregatskapazität und -Auslastung anzeigen.



== Über diese Aufgabe

Auf diesen Seiten werden Informationen angezeigt, beispielsweise die verfügbare Kapazität auf der lokalen Performance-Tier und auf der Cloud-Tier. Sie erfahren, wie viel Kapazität in beiden Tiers verwendet wird, welche Aggregate an ein Cloud-Tier angebunden sind. Welche Volumes die Funktionen von FabricPool implementieren, indem bestimmte Informationen in das Cloud-Tier verschoben werden



== Schritte

. Führen Sie einen der folgenden Schritte aus:
+
|===
| So zeigen Sie Kapazitätsinformationen für... | Tun Sie das... 


 a| 
Cluster
 a| 
.. Klicken Sie auf der Seite „Systemzustand/Cluster-Inventar“ auf ein Cluster.
.. Klicken Sie auf der Seite Health/Cluster Details auf die Registerkarte *Konfiguration*.
+
Auf der Anzeige werden die Namen aller Cloud-Tiers angezeigt, mit denen dieses Cluster verbunden ist.





 a| 
Aggregate
 a| 
.. Klicken Sie auf der Seite „Systemzustand/Aggregate Inventory“ auf ein Aggregat, in dem das Feld Typ „`SSD (FabricPool)`“ anzeigt.
.. Klicken Sie auf der Detailseite „Systemzustand/Aggregat“ auf die Registerkarte *Kapazität*.
+
Das Display zeigt die Gesamtkapazität sowie den belegten und freien Speicherplatz im Cloud-Tier an.

.. Klicken Sie auf die Registerkarte *Disk Information*.
+
Das Display zeigt den Namen der Cloud-Tier und den verfügbaren Speicherplatz an.

.. Klicken Sie auf die Registerkarte *Konfiguration*.
+
Das Display zeigt den Namen der Cloud-Tier sowie weitere detaillierte Informationen zum Objektspeicher an.





 a| 
Volumes
 a| 
.. Klicken Sie auf der Seite „System/Volume-Inventar“ auf ein Volume, auf dem im Feld „`Tiering Policy`“ ein Richtlinienname angezeigt wird.
.. Klicken Sie auf der Seite Health/Volume Details auf die Registerkarte *Konfiguration*.
+
Auf der Anzeige wird der Name der FabricPool-Tiering-Richtlinie angezeigt, die dem Volume zugewiesen ist.



|===




== Nachdem Sie fertig sind

Weitere Informationen zu FabricPool-Aggregaten finden Sie im Power Guide_ „ _ONTAP 9 Festplatten und Aggregate“.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["ONTAP 9 Festplatten und Aggregate Power Guide"]
