---
permalink: online-help/task-viewing-the-volume-list-and-details.html 
sidebar: sidebar 
keywords:  
summary: Auf der Seite „Status/Volume Inventory“ können Sie das Inventar der Volumes überwachen. Auf der Seite Systemzustand/Volumes Kapazität und Auslastung werden Informationen über die Kapazität und Auslastung der Volumes in einem Cluster angezeigt. 
---
= Anzeigen der Volume-Liste und der Details
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Status/Volume Inventory“ können Sie das Inventar der Volumes überwachen. Auf der Seite Systemzustand/Volumes Kapazität und Auslastung werden Informationen über die Kapazität und Auslastung der Volumes in einem Cluster angezeigt.



== Bevor Sie beginnen

Sie müssen über die Rolle „Operator“, „OnCommand Administrator“ oder „Storage Administrator“ verfügen.



== Über diese Aufgabe

Auf der Seite „Systemzustand/Volume-Details“ finden Sie zudem detaillierte Informationen zu überwachten Volumes, darunter Kapazität, Effizienz, Konfiguration und Sicherung der Volumes. Sie können auch Informationen zu den zugehörigen Geräten und zugehörigen Warnmeldungen für ein bestimmtes Volume anzeigen.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Systemzustand* > *Volumes*.
. Es gibt folgende Möglichkeiten, die Volume-Details anzuzeigen:
+
** Um detaillierte Informationen zur Kapazität und Auslastung von Volumes in einem Cluster anzuzeigen, wählen Sie im Menü Ansicht die Option *Volume-Kapazität und -Auslastung*.
** Um minimale Details anzuzeigen, positionieren Sie den Cursor über den Namen der Lautstärke.
** Klicken Sie zum Einblenden der vollständigen Details auf den Volume-Namen.
+
Sie können die vollständigen Details auch anzeigen, indem Sie im Dialogfeld mit den minimalen Details auf *Details anzeigen* klicken.



. Zeigen Sie die Objekte an, die mit dem Volumen in Verbindung stehen, indem Sie im Dialogfeld mit den minimalen Details auf *Related* klicken.

