---
settings:
  name: OnCommand Unified Manager 9.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: OnCommand Unified Manager 9.5 - Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/release-notes.html"
  - title: Los geht's
    entries:
    - title: Schnellstartinstallation für VMware vSphere
      url: "/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: "/release-notes.html"
    - title: Schnellstartinstallation für VMware vSphere
      url: qsg-vapp.html
    - title: Schnellstartinstallation für Linux
      url: qsg-linux.html
    - title: Schnellstartinstallation für Windows
      url: qsg-windows.html
  - title: Installation Konfiguration von Unified Manager
    links:
    - title: Installieren Sie das Upgrade auf VMware vSphere Systemen
      url: install/concept-installing-upgrading-and-removing-unified-manager-software-on-vmware-vsphere.html
    - title: Upgrade auf Linux-Systemen installieren
      url: install/concept-install-upgrade-and-remove-unified-manager-software.html
    - title: Installieren Sie das Upgrade auf Windows-Systemen
      url: install/concept-installing-upgrading-and-removing-unified-manager-software.html
    - title: Konfiguration Von Unified Manager
      url: config/concept-configuring-unified-manager.html
  - title: Performance Monitoring
    links:
    - title: Performance-Schwellenwerte
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: Cluster-Performance
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
  - title: Mehr Ressourcen
    links:
    - title: Unified Manager Videos
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager Blogs
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English]
    - title: Dokumentation für die neueste Version von Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
