---
permalink: qsg-vapp.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, VMWare QSG, vApp QSG, quick installation 
summary: Kurzanleitung für Unified Manager auf VMware vSphere Plattform. 
---
= Schnellstartanleitung für VMware Installationen
:allow-uri-read: 




== Systemanforderungen

* Betriebssystem VMware ESXi 5.5, 6.0 und 6.5
* RAM: 12 GB
* CPU: Insgesamt 9572 MHz
* Freier Speicherplatz: 5 GB (Thin Provisioning), 152 GB (Thick Provisioning)


Detaillierte Systemanforderungen finden Sie unter link:install/reference-vmware-software-and-installation-requirements.html["VMware Software- und Installationsanforderungen"] Und link:http://mysupport.netapp.com/matrix["Interoperabilitätsmatrix"].



== Installation von OnCommand Unified Manager



=== Laden Sie das Installationsprogramm herunter

. Laden Sie die herunter `OnCommandUnifiedManager-9.5RC1.ovas` Installationspaket.
. Speichern Sie die Datei in einem lokalen Verzeichnis oder Netzwerkverzeichnis, auf das Ihr vSphere Client zugreifen kann.




=== Installation Von Unified Manager

VMware Tools sind nicht im Unified Manager Installationspaket enthalten. Sie müssen ein CD-ROM- oder ISO-Image mounten, um es als Teil des Unified Manager-Installationsprozesses zu installieren.

. Klicken Sie im vSphere-Client auf *Datei > OVF-Vorlage bereitstellen*.
. Suchen Sie die OVA-Datei und stellen Sie die virtuelle Appliance mithilfe des Assistenten auf dem ESXi-Server bereit.
. Füllen Sie auf der Seite Netzwerkkonfiguration auf der Registerkarte Eigenschaften die Felder aus, die für den Installationstyp erforderlich sind, den Sie durchführen:
+
** Für eine statische Konfiguration: Geben Sie erforderliche Informationen in alle Felder ein (sekundäre DNS ist nicht erforderlich).
** Bei DHCP unter Verwendung von IPv4 lassen Sie alle Felder leer.
** Für DHCP unter Verwendung von IPv6: Aktivieren Sie das Feld „Automatische IPv6-Adresse aktivieren“, und lassen Sie alle anderen Felder leer.


. Schalten Sie die VM ein.
. Klicken Sie auf die Registerkarte Konsole, um den anfänglichen Startvorgang anzuzeigen.
. Folgen Sie der Eingabeaufforderung, um VMware Tools auf der VM zu installieren.
. Zeitzone konfigurieren.
. Geben Sie einen Benutzernamen und ein Passwort für die Unified Manager-Wartung ein.


Am Ende der Installation werden die Informationen zur Verbindung mit der Unified Manager Web-Benutzeroberfläche angezeigt.
