---
permalink: qsg-windows.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Windows QSG, quick installation, Windows installer 
summary: Kurzanleitung für Unified Manager auf der Linux-Plattform. 
---
= Kurzanleitung für Windows-Installationen
:allow-uri-read: 




== Systemanforderungen

* Betriebssysteme: Microsoft Windows Server 2012, 2012 R2, 2016 64-Bit Standard und Datacenter Edition
* RAM: 12 GB
* CPU: Insgesamt 9572 MHz
* Freier Speicherplatz: 100 GB Festplattenspeicher für das Installationsverzeichnis, 50 GB Festplattenspeicher für das MySQL-Datenverzeichnis


Detaillierte Systemanforderungen finden Sie unter link:install/reference-windows-software-and-installation-requirements.html["Windows Software- und Installationsanforderungen"] Und link:http://mysupport.netapp.com/matrix["Interoperabilitätsmatrix"].



== Installation von OnCommand Unified Manager



=== Laden Sie das Installationsprogramm herunter

. Laden Sie die herunter `OnCommandUnifiedManager-9.5RC1.exes` Installationspaket.
. Kopieren Sie die Installationsdatei in ein Verzeichnis auf dem Zielsystem.




=== Installation Von Unified Manager

Microsoft .NET 4.5 oder höher muss installiert sein. Unified Manager installiert im Rahmen der Installation weitere erforderliche Pakete von Drittanbietern. Weitere Informationen zu den abhängigen Softwarepaketen finden Sie unter link:install/concept-installing-upgrading-and-removing-unified-manager-software.html["Installieren, Aktualisieren und Entfernen der Unified Manager-Software unter Windows"].

. Melden Sie sich unter Windows mit dem lokalen Standardkonto an.
. Klicken Sie in dem Verzeichnis, in dem Sie die Installationsdatei heruntergeladen haben, mit der rechten Maustaste auf die ausführbare Datei Unified Manager (.exe) als Administrator.
. Geben Sie bei der entsprechenden Aufforderung den Benutzernamen und das Passwort ein, um den Unified Manager-Wartungs-Benutzer zu erstellen.
. Geben Sie im Datenbankverbindungsassistenten das MySQL-Root-Passwort ein.
. Befolgen Sie die verbleibenden Anweisungen, um die Installation abzuschließen.
. Klicken Sie am Ende der Installation auf *Fertig stellen* und die Unified Manager Web-Benutzeroberfläche wird angezeigt.

