---
permalink: performance-checker/concept-unified-manager-interfaces-used-to-manage-storage-system-performance.html 
sidebar: sidebar 
keywords:  
summary: 'Es gibt zwei Benutzeroberflächen, die OnCommand Unified Manager für das Monitoring und die Behebung von Performance-Problemen im Storage bereitstellt: Die webbasierte Benutzeroberfläche und die Wartungskonsole.' 
---
= Unified Manager-Schnittstellen zum Management der Storage-Systemperformance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Es gibt zwei Benutzeroberflächen, die OnCommand Unified Manager für das Monitoring und die Behebung von Performance-Problemen im Storage bereitstellt: Die webbasierte Benutzeroberfläche und die Wartungskonsole.



== Unified Manager Web-UI

Die Web-UI von Unified Manager ermöglicht Administratoren das Überwachen und Beheben von Performance-bezogenen Storage-Problemen.

In diesem Abschnitt werden einige gängige Workflows beschrieben, die ein Administrator zur Behebung von Problemen mit der Storage-Performance ausführen kann, die in der Weboberfläche von Unified Manager angezeigt werden.



== Wartungskonsole

Die Wartungskonsole ermöglicht einem Administrator, Betriebssystemprobleme, Probleme mit dem Versionsaufrüstungs-, Benutzer-Zugriffsprobleme und Netzwerkprobleme im Zusammenhang mit dem Unified Manager Server selbst zu überwachen, zu diagnostizieren und zu beheben. Wenn die Web-UI von Unified Manager nicht verfügbar ist, stellt die Wartungskonsole die einzige Zugriffsmöglichkeit auf Unified Manager dar.

Dieser Abschnitt enthält eine Anleitung zum Zugriff auf die Wartungskonsole und zur Behebung von Problemen im Zusammenhang mit der Funktionsweise des Unified Manager-Servers.
