---
permalink: performance-checker/concept-types-of-workloads-monitored-by-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: 'Mit Unified Manager lässt sich die Performance von zwei Workload-Typen überwachen: Benutzerdefiniert und systemdefiniert.' 
---
= Arten von Workloads, die von Unified Manager überwacht werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit Unified Manager lässt sich die Performance von zwei Workload-Typen überwachen: Benutzerdefiniert und systemdefiniert.

* *_benutzerdefinierte Workloads_*
+
Der I/O-Durchsatz von Applikationen zum Cluster. Dies sind Prozesse, die an Lese- und Schreibanfragen beteiligt sind. Ein FlexVol Volume oder FlexGroup Volume ist ein benutzerdefinierter Workload.

+
[NOTE]
====
Unified Manager überwacht nur die Workload-Aktivität auf dem Cluster. Er überwacht nicht die Applikationen, Clients oder Pfade zwischen den Applikationen und dem Cluster.

====
+
Wenn eine oder mehrere der folgenden Optionen für einen Workload zutrifft, kann er nicht von Unified Manager überwacht werden:

+
** Es handelt sich um eine Kopie der Datensicherung (DP) im schreibgeschützten Modus. (Beachten Sie, dass bei Verwendung von ONTAP 8.3 und höher DP-Volumes für vom Benutzer erzeugten Datenverkehr überwacht werden.)
** Es handelt sich um ein Infinite Volume.
** Ein offline-Datenklon.
** Es handelt sich um ein gespiegeltes Volume in einer MetroCluster-Konfiguration.


* *_systemdefinierte Workloads_*
+
Zu den internen Prozessen, die mit Storage-Effizienz, Datenreplizierung und Systemzustand verbunden sind, gehören:

+
** Storage-Effizienz, z. B. Deduplizierung
** Der Zustand der Festplatte, einschließlich RAID-Rekonstruktion, Disk-Schrubben usw.
** Datenreplizierung, z. B. SnapMirror Kopien
** Management-Aktivitäten
** Systemzustand des File-Systems, der verschiedene WAFL-Aktivitäten umfasst
** Filesystem-Scanner, z. B. WAFL-Scan
** Copy-Offload, z. B. Verlagerung von Storage-Effizienzvorgängen von VMware Hosts
** Systemzustand, wie z. B. das Verschieben von Volumes, die Datenkomprimierung usw.
** Nicht überwachte Volumes




Performance-Daten für systemdefinierte Workloads werden nur in der GUI angezeigt, wenn die von diesen Workloads verwendete Cluster-Komponente mit Konflikten belegt ist. Sie können beispielsweise nicht nach dem Namen eines systemdefinierten Workloads suchen, um dessen Performance-Daten in der GUI anzuzeigen. Wenn mehrere systemdefinierte Workloads desselben Typs angezeigt werden, wird dem Workload-Namen ein Buchstabe angehängt. Das Schreiben ist für die Verwendung durch das Supportpersonal bestimmt.
