---
permalink: health-checker/task-resolving-capacity-issues.html 
sidebar: sidebar 
keywords:  
summary: Dieser Workflow bietet ein Beispiel dafür, wie Sie ein Kapazitätsproblem lösen können. In diesem Szenario sind Sie Administrator oder Operator und haben Zugriff auf die Seite Unified Manager Dashboards/Überblick, um zu sehen, ob eines der überwachten Speicherobjekte Kapazitätsprobleme haben. Sie sehen, dass ein Volume mit einem Kapazitätsrisiko besteht und möchten die mögliche Ursache und Lösung des Problems herausfinden. 
---
= Behebung von Kapazitätsproblemen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dieser Workflow bietet ein Beispiel dafür, wie Sie ein Kapazitätsproblem lösen können. In diesem Szenario greifen Sie als Administrator oder Operator auf die Seite Unified ManagerDashboards/Überblick zu, um zu sehen, ob eines der überwachten Speicherobjekte Kapazitätsprobleme haben. Sie sehen, dass ein Volume mit einem Kapazitätsrisiko besteht und möchten die mögliche Ursache und Lösung des Problems herausfinden.



== Bevor Sie beginnen

Sie müssen über die Rolle „Operator“, „OnCommand Administrator“ oder „Storage Administrator“ verfügen.



== Über diese Aufgabe

Auf der Seite Dashboards/Überblick sehen Sie sich den Bereich ungelöste Vorfälle und Risiken an und Sie sehen ein Fehlerereignis „`Volume Space Full`“ im Teilfenster „Kapazität“ unter „SVM Volume Capacity“, das gefährdet ist.



== Schritte

. Klicken Sie im Bereich *ungelöste Vorfälle und Risiken* auf der Seite *Dashboards/Übersicht* auf den Namen des Ereignisses des vollständigen Volume-Raums im Fensterbereich *Kapazität*.
+
Die Seite Ereignisdetails für den Fehler wird angezeigt.

. Auf der Seite *Event* Details können Sie eine oder mehrere der folgenden Aufgaben ausführen:
+
** Überprüfen Sie die Fehlermeldung im Feld Ursache, und klicken Sie auf die Vorschläge unter vorgeschlagene Korrekturmaßnahmen, um Beschreibungen möglicher Korrekturmaßnahmen zu prüfen. xref:task-performing-suggested-remedial-actions-for-a-full-volume.adoc[Durchführung von vorgeschlagenen Abhilfemaßnahmen für ein vollständiges Volumen]
** Klicken Sie im Feld Quelle auf den Objektnamen, in diesem Fall ein Volume, um Details zum Objekt anzuzeigen. xref:reference-health-volume-details-page.adoc[Einzelheiten zu den Volumes]
** Suchen Sie nach Notizen, die zu diesem Event hinzugefügt wurden. xref:task-adding-and-reviewing-notes-about-an-event.adoc[Hinzufügen und Prüfen von Notizen zu einem Ereignis]
** Fügen Sie dem Ereignis eine Notiz hinzu. xref:task-adding-and-reviewing-notes-about-an-event.adoc[Hinzufügen und Prüfen von Notizen zu einem Ereignis]
** Das Ereignis einem anderen Benutzer zuweisen. xref:task-assigning-events-to-specific-users.adoc[Ereignisse werden zugewiesen]
** Bestätigen Sie das Ereignis. xref:task-acknowledging-and-resolving-events.adoc[Bestätigen und Beheben von Ereignissen]
** Markieren Sie das Ereignis als erledigt. xref:task-acknowledging-and-resolving-events.adoc[Bestätigen und Beheben von Ereignissen]



