---
permalink: health-checker/task-creating-a-snapvault-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: Sie können eine SnapVault-Beziehung auf der Seite „Systemzustand/Volume-Details“ erstellen, sodass Daten-Backups für Sicherungszwecke auf Volumes aktiviert sind. 
---
= Erstellen einer SnapVault-Schutzbeziehung auf der Seite „Health/Volume Details“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine SnapVault-Beziehung auf der Seite „Systemzustand/Volume-Details“ erstellen, sodass Daten-Backups für Sicherungszwecke auf Volumes aktiviert sind.



== Bevor Sie beginnen

* Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen Workflow Automation einrichten, um diese Aufgabe auszuführen.




== Über diese Aufgabe

Das Menü * Protect* wird in den folgenden Fällen nicht angezeigt:

* Wenn die RBAC-Einstellungen diese Aktion nicht zulassen, z. B. wenn Sie nur über Operatorrechte verfügen
* Wenn die Volume-ID unbekannt ist, z. B. wenn eine Intercluster-Beziehung vorhanden ist und der Ziel-Cluster noch nicht erkannt wurde




== Schritte

. Klicken Sie auf der Registerkarte *Schutz* der Detailseite *Gesundheit/Volumen* mit der rechten Maustaste auf ein Volume in der Topologieansicht, die Sie schützen möchten.
. Wählen Sie im Menü * Protect* > *SnapVault* aus.
+
Das Dialogfeld Schutz konfigurieren wird gestartet.

. Klicken Sie auf *SnapVault*, um die Registerkarte *SnapVault* anzuzeigen und die Informationen zur sekundären Ressource zu konfigurieren.
. Klicken Sie auf *Erweitert*, um Deduplizierung, Komprimierung, Autogrow und Platzgarantie nach Bedarf festzulegen und klicken Sie dann auf *Apply*.
. Füllen Sie im Dialogfeld *Schutz konfigurieren* den Bereich *Zielinformationen* und den Bereich *Beziehungseinstellungen* aus.
. Klicken Sie Auf *Anwenden*.
+
Sie gelangen zurück zur Seite „Health/Volume Details“.

. Klicken Sie oben auf der Seite *Health/Volume* Details auf den Link für die Schutzkonfiguration.
+
Die Seite Schutz-/Jobdetails wird angezeigt.

. Klicken Sie auf *Aktualisieren*, um die Aufgabenliste und die Aufgabendetails zu aktualisieren, die mit dem Konfigurationsauftrag für den Schutz verknüpft sind, und um festzustellen, wann der Job abgeschlossen ist.
+
Wenn die Aufgabenstellungen abgeschlossen sind, werden die neuen Beziehungen auf der Topologieansicht „Systemzustand/Volume-Details“ angezeigt.


