---
permalink: health-checker/task-generating-and-uploading-a-support-bundle.html 
sidebar: sidebar 
keywords:  
summary: Sie können ein Support-Paket mit vollständigen Diagnoseinformationen erstellen, damit Sie es dann abrufen und an den technischen Support zur Fehlerbehebung senden können. Da einige Datentypen große Mengen von Cluster-Ressourcen verwenden oder lange in die Fertigstellung benötigen, können Sie Datentypen angeben, die in das Support-Bundle einbezogen oder ausgeschlossen werden sollen. 
---
= Erstellen eines Support-Bundles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Support-Paket mit vollständigen Diagnoseinformationen erstellen, damit Sie es dann abrufen und an den technischen Support zur Fehlerbehebung senden können. Da einige Datentypen große Mengen von Cluster-Ressourcen verwenden oder lange in die Fertigstellung benötigen, können Sie Datentypen angeben, die in das Support-Bundle einbezogen oder ausgeschlossen werden sollen.



== Bevor Sie beginnen

Sie müssen als Wartungbenutzer Zugriff auf die Wartungskonsole haben.



== Über diese Aufgabe

Unified Manager speichert nur die zwei zuletzt erstellten Support Bundles. Ältere Supportpakete werden aus dem System gelöscht.

[NOTE]
====
Auf Windows-Systemen, der Befehl `supportbundle.bat` Wird zur Generierung eines Support Bundle nicht mehr unterstützt.

====


== Schritte

. Wählen Sie in der Wartungskonsole *Hauptmenü* die Option *Support/Diagnose*.
. Wählen Sie *Support Bundle Generieren* Aus.
. Wählen oder deaktivieren Sie die folgenden Datentypen aus, die im Supportpaket enthalten oder ausgeschlossen werden sollen:
+
** *Datenbankauszug*
+
Ein Dump der MySQL Server Datenbank.

** *Haufendump*
+
Ein Snapshot des Status der wichtigsten Unified Manager Serverprozesse. Diese Option ist standardmäßig deaktiviert und sollte nur ausgewählt werden, wenn sie vom Kundendienst angefordert wird.

** *Aufnahmeaufzeichnungen*
+
Eine Aufzeichnung der gesamten Kommunikation zwischen Unified Manager und den überwachten Clustern.



+
[NOTE]
====
Wenn Sie die Auswahl aller Datentypen aufheben, wird das Support-Paket immer noch mit anderen Unified Manager-Daten generiert.

====
. Typ `g`, Und drücken Sie dann die Eingabetaste, um das Supportpaket zu generieren.
+
Da es sich bei der Generierung eines Support-Bundles um einen speicherintensiven Vorgang handelt, werden Sie aufgefordert zu überprüfen, ob Sie das Support-Bundle derzeit sicher erstellen möchten.

. Typ `y`, Und drücken Sie dann die Eingabetaste, um das Supportpaket zu generieren.
+
Wenn Sie das Support-Bundle derzeit nicht generieren möchten, geben Sie ein `n`, Und drücken Sie dann die Eingabetaste.

. Wenn Sie Datenbank-Dump-Dateien in das Support-Bundle aufgenommen haben, werden Sie aufgefordert, den Zeitraum anzugeben, für den Performance-Statistiken enthalten sein sollen. Das Einführen von Performance-Statistiken kann viel Zeit und Speicherplatz beanspruchen, sodass Sie auch eine Dump-Datenbank ohne inklusive der Performance-Statistiken erstellen können:
+
.. Geben Sie das Startdatum im Format YYYYMMDD ein.
+
Geben Sie beispielsweise ein `20170101` Für den 1. Januar 2017. Eingabe `n` Wenn Sie nicht möchten, dass Performance-Statistiken aufgenommen werden sollen.

.. Geben Sie die Anzahl der Tage der einzuführenden Statistiken ab 12 Uhr ein Am angegebenen Startdatum.
+
Sie können eine Zahl zwischen 1 und 10 eingeben.



+
Wenn Sie Performance-Statistiken vorhalten, zeigt das System den Zeitraum an, für den Performance-Statistiken erfasst werden sollen.

. Wählen Sie *Support Bundle Generieren* Aus.
+
Das generierte Supportpaket befindet sich im `/support` Verzeichnis.





== Nachdem Sie fertig sind

Nach dem Generieren des Support-Pakets können Sie es mithilfe eines SFTP-Clients oder unter Verwendung von UNIX- oder Linux-CLI-Befehlen abrufen. Unter Windows-Installationen können Sie Remote Desktop (RDP) verwenden, um das Supportpaket abzurufen.

Das generierte Supportpaket befindet sich im `/support` Verzeichnis auf VMware Systemen, in `/opt/netapp/data/support/` Auf Linux-Systemen und in `ProgramData\NetApp\OnCommandAppData\ocum\support` Auf Windows-Systemen.
