---
permalink: health-checker/task-disabling-saml-authentication-from-the-maintenance-console-um.html 
sidebar: sidebar 
keywords:  
summary: Wenn kein Zugriff auf die Unified Manager GUI besteht, müssen Sie möglicherweise die SAML-Authentifizierung von der Wartungskonsole aus deaktivieren. Dies kann in Fällen einer Fehlkonfiguration auftreten oder wenn der IdP nicht zugänglich ist. 
---
= Deaktivieren der SAML-Authentifizierung über die Wartungskonsole
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn kein Zugriff auf die Unified Manager GUI besteht, müssen Sie möglicherweise die SAML-Authentifizierung von der Wartungskonsole aus deaktivieren. Dies kann in Fällen einer Fehlkonfiguration auftreten oder wenn der IdP nicht zugänglich ist.



== Bevor Sie beginnen

Sie müssen als Wartungbenutzer Zugriff auf die Wartungskonsole haben.



== Über diese Aufgabe

Wenn die SAML-Authentifizierung deaktiviert ist, führen die konfigurierten Verzeichnisdienstanbieter wie Active Directory oder LDAP eine Anmeldeauthentifizierung durch. Lokale Benutzer und Wartungbenutzer können zusätzlich zu konfigurierten Remote-Benutzern auf die grafische Benutzeroberfläche zugreifen.

Sie können die SAML-Authentifizierung auch über die Seite Setup/Authentifizierung in der UI deaktivieren.

[NOTE]
====
Unified Manager wird automatisch neu gestartet, nachdem die SAML-Authentifizierung deaktiviert ist.

====


== Schritte

. Melden Sie sich bei der Wartungskonsole an.
. Geben Sie im *Hauptmenü* die Nummer für die Option *SAML-Authentifizierung deaktivieren* ein.
+
Es wird eine Meldung angezeigt, die bestätigt, dass die SAML-Authentifizierung deaktiviert und Unified Manager neu gestartet werden soll.

. Geben Sie *y* ein, und drücken Sie dann die Eingabetaste, und Unified Manager wird neu gestartet.




== Ergebnisse

Wenn Remote-Benutzer das nächste Mal versuchen, auf die grafische Benutzeroberfläche von Unified Manager zuzugreifen, geben sie ihre Anmeldedaten auf der Anmeldeseite von Unified Manager anstelle der IdP-Anmeldeseite ein.



== Nachdem Sie fertig sind

Greifen Sie bei Bedarf auf Ihr IdP zu, und löschen Sie die URL und Metadaten des Unified Manager-Servers.
