---
permalink: health-checker/task-configuring-global-qtree-health-threshold-values.html 
sidebar: sidebar 
keywords:  
summary: Sie können die globalen Schwellenwerte für den Systemzustand für alle qtrees konfigurieren, um Schwellenverletzungen zu verfolgen. Geeignete Ereignisse werden zum Erreichen von Gesundheitsschwellenwerten generiert und anhand dieser Ereignisse können vorbeugende Maßnahmen ergriffen werden. Sie können die globalen Werte anhand der Best Practice-Einstellungen für Schwellenwerte konfigurieren, die für alle überwachten qtrees gelten. 
---
= Konfigurieren von globalen qtree-Zustandsschwellenwerten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die globalen Schwellenwerte für den Systemzustand für alle qtrees konfigurieren, um Schwellenverletzungen zu verfolgen. Geeignete Ereignisse werden zum Erreichen von Gesundheitsschwellenwerten generiert und anhand dieser Ereignisse können vorbeugende Maßnahmen ergriffen werden. Sie können die globalen Werte anhand der Best Practice-Einstellungen für Schwellenwerte konfigurieren, die für alle überwachten qtrees gelten.



== Bevor Sie beginnen

Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.



== Über diese Aufgabe

Die Schwellenwertoptionen verfügen über Standardwerte für eine bessere Überwachung, Sie können diese jedoch an die Anforderungen Ihrer Umgebung anpassen.

Ereignisse werden nur dann für einen qtree erzeugt, wenn ein qtree Kontingent oder eine Standard-Quote auf dem qtree festgelegt wurde. Ereignisse werden nicht generiert, wenn der in einem Benutzerkontingent oder Gruppenkontingent definierte Speicherplatz den Schwellenwert überschritten hat.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Konfiguration* > *Health Schwellenwerte*.
. Klicken Sie auf der Seite *Konfiguration/Gesundheit Schwellenwerte* auf *Qtrees*.
. Konfigurieren Sie die entsprechenden Kapazitätsschwellenwerte.
. Klicken Sie Auf *Speichern*.

