---
permalink: config/task-adding-clusters.html 
sidebar: sidebar 
keywords:  
summary: Sie können OnCommand Unified Manager um ein Cluster erweitern, sodass Sie das Cluster überwachen können. Dazu gehört beispielsweise die Möglichkeit, Cluster-Informationen wie Systemzustand, Kapazität, Performance und Konfiguration des Clusters abzurufen, damit Sie etwaige auftretende Probleme finden und beheben können. 
---
= Hinzufügen von Clustern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können OnCommand Unified Manager um ein Cluster erweitern, sodass Sie das Cluster überwachen können. Dazu gehört beispielsweise die Möglichkeit, Cluster-Informationen wie Systemzustand, Kapazität, Performance und Konfiguration des Clusters abzurufen, damit Sie etwaige auftretende Probleme finden und beheben können.



== Bevor Sie beginnen

* Sie müssen über die Rolle „OnCommand Administrator“ oder „Speicheradministrator“ verfügen.
* Sie müssen die folgenden Informationen haben:
+
** Host-Name oder Cluster-Management-IP-Adresse
+
Der Hostname ist der FQDN oder der Kurzname, den Unified Manager zur Verbindung mit dem Cluster verwendet. Der Host-Name muss bis zur Cluster-Management-IP-Adresse aufgelöst werden.

+
Die Cluster-Management-IP-Adresse muss die Cluster-Management-LIF der administrativen Storage Virtual Machine (SVM) sein. Wenn Sie eine Node-Management-LIF verwenden, schlägt der Vorgang fehl.

** Benutzername und Passwort für den Data ONTAP-Administrator
+
Für dieses Konto muss die Rolle _admin_ mit dem Anwendungszugriff auf _ontapi_, _ssh_ und _http_ eingestellt sein.

** Typ des Protokolls (HTTP oder HTTPS), der auf dem Cluster konfiguriert werden kann und die Portnummer, die zum Herstellen einer Verbindung zum Cluster verwendet wird


+
[NOTE]
====
Sie können Cluster hinzufügen, die sich hinter einer NAT/Firewall befinden, indem Sie die Unified Manager NAT IP-Adresse verwenden. Alle angeschlossenen Workflow-Automatisierungs- oder SnapProtect-Systeme müssen sich auch hinter der NAT/Firewall befinden, und SnapProtect-API-Aufrufe müssen die NAT-IP-Adresse verwenden, um den Cluster zu identifizieren.

====
* Der FQDN des Unified Managers muss in der Lage sein, das ONTAP-System zu pingen.
+
Sie können dies mit dem folgenden ONTAP-Befehl überprüfen: `ping -node node_name -destination Unified_Manager_FQDN`.

* Auf dem Unified Manager-Server muss ausreichend Speicherplatz vorhanden sein. Sie können dem Server kein Cluster hinzufügen, wenn mehr als 90 % des Speicherplatzes im Datenbankverzeichnis bereits belegt sind.




== Über diese Aufgabe

Für eine MetroCluster Konfiguration müssen Sie sowohl die lokalen als auch die Remote-Cluster hinzufügen, und die Cluster müssen korrekt konfiguriert sein.

Sie können ein einzelnes Cluster durch zwei Instanzen von Unified Manager überwachen, vorausgesetzt, Sie haben eine zweite Cluster-Management-LIF im Cluster konfiguriert, sodass jede Instanz von Unified Manager über eine andere LIF verbunden ist.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Konfiguration* > *Cluster-Datenquellen*.
. Klicken Sie auf der Seite *Konfiguration/Cluster-Datenquellen* auf *Hinzufügen*.
. Geben Sie im Dialogfeld *Cluster hinzufügen* die erforderlichen Werte an, z. B. Hostname oder IP-Adresse des Clusters, Benutzername, Passwort, Protokoll für die Kommunikation und Portnummer.
+
Standardmäßig sind das HTTPS-Protokoll und Port 443 ausgewählt.

+
Sie können die Cluster-Management-IP-Adresse von IPv6 zu IPv4 oder von IPv4 zu IPv6 ändern. Die neue IP-Adresse wird im Cluster-Raster und die Seite der Cluster-Konfiguration nach Abschluss des nächsten Überwachungszyklus angezeigt.

. Klicken Sie Auf *Absenden*.
. Wenn HTTPS ausgewählt ist, führen Sie die folgenden Schritte aus:
+
.. Klicken Sie im Dialogfeld *Autorisieren Host* auf *Zertifikat anzeigen*, um die Zertifikatsinformationen zum Cluster anzuzeigen.
.. Klicken Sie Auf *Ja*.
+
Unified Manager überprüft das Zertifikat nur, wenn das Cluster zunächst hinzugefügt wird. Unified Manager überprüft nicht das Zertifikat für jeden API-Aufruf an ONTAP.

+
Wenn das Zertifikat abgelaufen ist, können Sie kein neues Cluster hinzufügen. Sie müssen zuerst das SSL-Zertifikat erneuern und dann den Cluster hinzufügen.







== Ergebnisse

Nachdem alle Objekte für ein neues Cluster erkannt wurden (ca. 15 Minuten), erfasst Unified Manager die historischen Performance-Daten der letzten 15 Tage. Diese Statistiken werden mithilfe der Funktionalität zur Datenerfassung erfasst. Diese Funktion bietet Ihnen sofort nach dem Hinzufügen mehr als zwei Wochen Performance-Informationen für einen Cluster. Nach Abschluss des Datenerfassungszyklus werden Cluster-Performance-Daten in Echtzeit standardmäßig alle fünf Minuten erfasst.

[NOTE]
====
Da die Sammlung von 15 Tagen Leistungsdaten CPU-intensiv ist, empfiehlt es sich, das Hinzufügen neuer Cluster zu staffeln, so dass Datenkontinuitätssammlung nicht auf zu vielen Clustern zur gleichen Zeit laufen. Wenn Sie Unified Manager während des Datenerfassungszeitraums neu starten, wird die Sammlung angehalten, und es werden für den fehlenden Zeitraum Lücken in den Leistungsdiagrammen angezeigt.

====
[TIP]
====
Wenn Sie eine Fehlermeldung erhalten, dass Sie das Cluster nicht hinzufügen können, prüfen Sie, ob die folgenden Probleme vorhanden sind:

* Wenn die Uhren auf den beiden Systemen nicht synchronisiert sind und das HTTPS-Zertifikat von Unified Manager nach dem Datum des Clusters liegt. Sie müssen sicherstellen, dass die Uhren mit NTP oder einem ähnlichen Dienst synchronisiert werden.
* Wenn der Cluster die maximale Anzahl von EMS-Benachrichtigungszielen erreicht hat, kann die Unified Manager-Adresse nicht hinzugefügt werden. Standardmäßig können nur 20 EMS-Benachrichtigungsziele auf dem Cluster definiert werden.


====