---
permalink: install/concept-browser-and-platform-requirements.html 
sidebar: sidebar 
keywords:  
summary: Für den Zugriff auf die Unified Manager-Benutzeroberfläche müssen Sie einen unterstützten Browser verwenden. 
---
= Unterstützte Browser
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für den Zugriff auf die Unified Manager-Benutzeroberfläche müssen Sie einen unterstützten Browser verwenden.

Unified Manager wurde mit den folgenden Browsern getestet, andere Browser können möglicherweise funktionieren, jedoch nicht qualifiziert sind. Eine vollständige Liste der unterstützten Browser-Versionen finden Sie in der Interoperabilitäts-Matrix.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

* Mozilla Firefox ESR 60
* Google Chrome Version 68 und 69
* Microsoft Internet Explorer 11


Wenn Sie für alle Browser Popup-Blocker deaktivieren, können Sie sicherstellen, dass die Softwarefunktionen ordnungsgemäß angezeigt werden.

Für Internet Explorer müssen Sie sicherstellen, dass die Kompatibilitätsansicht deaktiviert ist und der Dokumentmodus auf den Standardmodus eingestellt ist. Informationen zu diesen Einstellungen finden Sie in der Microsoft IE-Dokumentation.

[NOTE]
====
Firefox und Chrome sind die bevorzugten Browser, da es einige Fälle gab, in denen komplexe UI-Seiten langsamer laden, wenn Internet Explorer.

====
Wenn Sie planen, Unified Manager für SAML-Authentifizierung so zu konfigurieren, dass ein Identitäts-Provider (IdP) Benutzer authentifiziert, überprüfen Sie die Liste der vom IdP unterstützten Browser.
