---
permalink: install/reference-red-hat-and-centos-software-and-installation-requirements.html 
sidebar: sidebar 
keywords:  
summary: Das Linux-System, auf dem Unified Manager installiert wird, erfordert bestimmte Versionen des Betriebssystems und unterstützende Software. 
---
= Anforderungen an Red hat Enterprise Linux und CentOS Software und Installation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Linux-System, auf dem Unified Manager installiert wird, erfordert bestimmte Versionen des Betriebssystems und unterstützende Software.



== Betriebssystem-Software

Das Linux-System muss die folgenden Versionen des Betriebssystems und die unterstützende Software installiert haben:

* Red hat Enterprise Linux oder CentOS 64-Bit Version 7.x
+
Red hat Enterprise Linux 6.x wird ab Unified Manager 9.4 nicht unterstützt.



In der Interoperabilitäts-Matrix finden Sie eine vollständige und aktuelle Liste der unterstützten Red hat Enterprise Linux- und CentOS-Versionen.

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

Folgende Drittanbieterpakete sind erforderlich:

* MySQL Community Edition Version 5.7.23 oder höhere Versionen in der 5.7-Familie (aus dem MySQL-Repository)
* OpenJDK Version 11 (aus dem Red hat Extra Enterprise Linux Server Repository)
+
[NOTE]
====
Oracle Java wird ab Unified Manager 9.5 nicht unterstützt.

====
* P7zip Version 16.02 oder höher (aus dem Red hat Extra Packages for Enterprise Linux Repository)


[NOTE]
====
Wenn Sie nach dem Ausführen von Unified Manager ein Upgrade der Drittanbieter-Software planen, müssen Sie Unified Manager zunächst herunterfahren. Nach Abschluss der Softwareinstallation von Drittanbietern können Sie Unified Manager neu starten.

====


== Anforderungen an die Benutzerautorisierung

Die Installation von Unified Manager auf einem Red hat Enterprise Linux System oder CentOS System kann vom Root-Benutzer oder von nicht-Root-Benutzern mit dem durchgeführt werden `sudo` Befehl.



== Installationsvoraussetzungen

Die Best Practices für die Installation von Red hat Enterprise Linux oder CentOS und den damit verbundenen Repositorys auf Ihrem System lauten wie folgt:

* Sie müssen Red hat Enterprise Linux oder CentOS nach Red hat Best Practices installieren, und Sie sollten die folgenden Standardoptionen wählen, die die Auswahl von "`SServer mit GUI`" erfordern.
* Bei der Installation von Unified Manager auf Red hat Enterprise Linux oder CentOS muss das System Zugriff auf das entsprechende Repository haben, damit das Installationsprogramm auf alle erforderlichen Softwareabhängigkeiten zugreifen und diese installieren kann.
* Für das `yum` Installer um die abhängige Software in den Red hat Enterprise Linux Repositorys zu finden, müssen Sie das System während der Red hat Enterprise Linux Installation oder danach unter Verwendung eines gültigen Red hat Subskriptions registriert haben.
+
Informationen zum Red hat Subscription Manager finden Sie in der Red hat Dokumentation.

* Sie müssen das EPEL-Repository (Extra Packages for Enterprise Linux) aktivieren, um die erforderlichen Dienstprogramme von Drittanbietern erfolgreich auf Ihrem System installieren zu können.
+
Wenn das EPEL-Repository auf Ihrem System nicht konfiguriert ist, müssen Sie das Repository manuell herunterladen und konfigurieren.

+
xref:task-manually-configuring-the-epel-repository.adoc[Manuelles Konfigurieren des EPEL-Repositorys]

* Wenn die korrekte Version von MySQL nicht installiert ist, müssen Sie das MySQL-Repository aktivieren, damit die MySQL-Software auf Ihrem System erfolgreich installiert werden kann.
+
Wenn das MySQL-Repository nicht auf Ihrem System konfiguriert ist, müssen Sie das Repository manuell herunterladen und konfigurieren.

+
xref:task-manually-configuring-the-mysql-repository.adoc[Manuelles Konfigurieren des MySQL-Repository]



Wenn Ihr System keinen Internetzugang hat und die Repositories nicht von einem mit dem Internet verbundenen System mit dem nicht verbundenen System gespiegelt werden, sollten Sie die Installationsanweisungen befolgen, um die externen Softwareabhängigkeiten Ihres Systems zu bestimmen. Anschließend können Sie die erforderliche Software auf das internetverbundene System herunterladen und die kopieren `.rpm` Dateien auf dem System, auf dem Unified Manager installiert werden soll. Um die Artefakte und Pakete herunterzuladen, müssen Sie das verwenden `yum install` Befehl. Sie müssen sicherstellen, dass auf beiden Systemen die gleiche Betriebssystemversion ausgeführt wird und dass die Abonnementlizenz für die entsprechende Red hat Enterprise Linux- oder CentOS-Version gilt.

[NOTE]
====
Sie dürfen die erforderliche Drittanbietersoftware nicht aus anderen als den hier aufgeführten Repositorys installieren. Die in den Red hat Repositorys installierte Software wurde speziell für Red hat Enterprise Linux entwickelt und entspricht den Best Practices von Red hat (Verzeichnislayouts, Berechtigungen usw.). Software von anderen Standorten folgt möglicherweise nicht diesen Richtlinien. Dies kann dazu führen, dass die Unified Manager-Installation fehlschlägt oder Probleme mit zukünftigen Upgrades verursachen kann.

====


== Port 443 erforderlich

Allgemeine Images von Red hat und CentOS blockieren externen Zugriff auf Port 443. Wenn die Verbindung zwischen Ihrem Browser und Ihrem OnCommand Produkt nicht hergestellt werden kann, ist dies möglicherweise das Problem. Der folgende Befehl ermöglicht den Zugriff auf Port 443 für alle externen Benutzer und Anwendungen: `# firewall-cmd –zone=public –add-port=443/tcp –permanent; firewall-cmd –reload`

Wenden Sie sich vor der Ausführung dieses Befehls an Ihre IT-Abteilung, um zu prüfen, ob für Ihre Sicherheitsrichtlinien ein anderes Verfahren erforderlich ist.
