---
permalink: install/task-upgrading-mysql-on-linux.html 
sidebar: sidebar 
keywords:  
summary: Sie können auf eine neuere Version von MySQL auf dem Linux-Server aktualisieren, auf dem Unified Manager installiert ist, um Korrekturen für Sicherheitslücken zu erhalten. 
---
= Aktualisieren von MySQL auf Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können auf eine neuere Version von MySQL auf dem Linux-Server aktualisieren, auf dem Unified Manager installiert ist, um Korrekturen für Sicherheitslücken zu erhalten.



== Bevor Sie beginnen

Sie müssen über Root-Rechte für das Linux-System verfügen, auf dem Unified Manager installiert ist.



== Über diese Aufgabe

Sie können nur ein Upgrade auf kleinere Updates von MySQL 5.7 durchführen, zum Beispiel 5.7.1 bis 5.7.2 . Sie können kein Upgrade auf die Hauptversionen von MySQL durchführen, z. B. Version 5.8.



== Schritte

. Melden Sie sich als Root-Benutzer auf dem Unified Manager-Hostcomputer an.
. Laden Sie den neuesten MySQL Community Server herunter `.rpm` Auf dem Zielsystem bündeln.
. Enttar das Paket in ein Verzeichnis auf dem Zielsystem.
. Sie erhalten mehrere `.rpm` Pakete im Verzeichnis nach dem Entrieten des Bundles, aber Unified Manager benötigt nur die folgenden rpm-Pakete:
+
** mysql-Community-Client-5.7.x
** mysql-Community-libs-5.7.x
** mysql-Community-Server-5.7.x
** mysql-Community-common-5.7.x
** mysql-Community-libs-compat-5.7.x Alle anderen löschen `.rpm` Pakete. Die Installation aller Pakete in einem rpm-Paket verursacht keine Probleme.


. Beenden Sie den Unified Manager-Service und die zugehörige MySQL-Software in der folgenden Reihenfolge:
. Rufen Sie das Upgrade von MySQL mit dem folgenden Befehl auf: `yum install *.rpm`
+
`*.rpm` Bezieht sich auf das `.rpm` Pakete in dem Verzeichnis, in dem Sie die neuere Version von MySQL heruntergeladen haben.

. Starten Sie Unified Manager in der angezeigten Reihenfolge:

