---
permalink: install/task-installing-unified-manager-linux.html 
sidebar: sidebar 
keywords:  
summary: Sie können Unified Manager auf einer physischen oder virtuellen Red hat Enterprise Linux oder CentOS Plattform installieren. 
---
= Installation von Unified Manager unter Red hat Enterprise Linux oder CentOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager auf einer physischen oder virtuellen Red hat Enterprise Linux oder CentOS Plattform installieren.



== Bevor Sie beginnen

* Das System, auf dem Unified Manager installiert werden soll, muss die System- und Softwareanforderungen erfüllen.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Hardwaresystemanforderungen]

+
xref:reference-red-hat-and-centos-software-and-installation-requirements.adoc[Anforderungen an Red hat und CentOS Software und Installation]

* Sie müssen Unified Manager heruntergeladen haben``.zip`` Datei von der NetApp Support Site auf das Zielsystem
* Sie benötigen einen unterstützten Webbrowser.
* Die Terminalemulationssoftware muss ScRollback aktiviert haben.




== Über diese Aufgabe

Das Red hat Enterprise Linux oder CentOS System kann alle erforderlichen Versionen der erforderlichen Hilfssoftware (Java, MySQL, zusätzliche Utilities) installiert haben, oder es kann nur einige der erforderlichen Software installiert haben, oder es kann ein neu installiertes System mit keiner der erforderlichen Software installiert sein.



== Schritte

. Melden Sie sich beim Server an, auf dem Sie Unified Manager installieren.
. Geben Sie die entsprechenden Befehle ein, um zu ermitteln, welche Software möglicherweise eine Installation oder ein Upgrade auf dem Zielsystem erforderlich ist, um die Installation zu unterstützen:
+
|===
| Erforderliche Software und Mindestversion | Befehl zum Überprüfen der Software und der Version 


 a| 
OpenJDK Version 11
 a| 
`java -version`



 a| 
MySQL 5.7.23 Community Edition
 a| 
`rpm -qa | grep -i mysql`



 a| 
P7zip 9.20.1
 a| 
`rpm -qa | grep p7zip`

|===
. Wenn eine beliebige Version der aufgeführten Software vor der erforderlichen Version liegt, geben Sie den entsprechenden Befehl ein, um das Modul zu deinstallieren:
+
|===
| Zu deinstallierenden Software | Befehl zum Deinstallieren der Software 


 a| 
MySQL

[NOTE]
====
Deinstallieren Sie alle Versionen, die nicht MySQL 5.7.23 Community Edition oder höher sind.

==== a| 
`rpm -e` <``mysql_package_name``>

[NOTE]
====
Wenn Sie Abhängigkeitsfehler erhalten, müssen Sie das hinzufügen `--nodeps` Option zum Deinstallieren der Komponente.

====


 a| 
Alle anderen Module
 a| 
`yum remove` `module_name`

|===
. Navigieren Sie zum Verzeichnis, in dem Sie die Installation heruntergeladen haben `.zip` Datei und Erweiterung des Unified Manager Bundles: `unzip OnCommandUnifiedManager-rhel7-9.5.zip`
+
Erforderlich `.rpm` Module für Unified Manager werden in das Zielverzeichnis entpackt.

. Stellen Sie sicher, dass die folgenden Module im Verzeichnis verfügbar sind: `ls *.rpm`
+
** `ocie-au-<version>.x86_64.rpm`
** `ocie-server-<version>.x86_64.rpm`
** `ocie-serverbase-<version>.x86_64.rpm`
** `netapp-application-server-<version>.x86_64.rpm`
** `netapp-platform-base-<version>.x86_64.rpm`
** `netapp-ocum-<version>.x86_64.rpm`


. Führen Sie das Skript vor der Installation aus, um sicherzustellen, dass keine Systemkonfigurationseinstellungen oder installierte Software vorhanden sind, die mit der Installation von Unified Manager in Konflikt geraten: `pre_install_check.sh`
+
Das Skript vor der Installation überprüft, ob das System über ein gültiges Red hat-Abonnement verfügt und dass es Zugriff auf die erforderlichen Software-Repositorys hat. Wenn das Skript Probleme erkennt, müssen Sie die Probleme vor der Installation von Unified Manager beheben.

+
[NOTE]
====
Sie müssen Schritt 7 _Only_ ausführen, wenn Sie die für Ihre Installation erforderlichen Pakete manuell herunterladen müssen. Wenn Ihr System über einen Internetzugang verfügt und alle erforderlichen Pakete verfügbar sind, fahren Sie mit Schritt 8 fort.

====
. Bei Systemen, die nicht mit dem Internet verbunden sind oder die Red hat Enterprise Linux-Repositories nicht verwenden, führen Sie die folgenden Schritte aus, um festzustellen, ob erforderliche Pakete fehlen und diese Pakete anschließend herunterladen:
+
.. Zeigen Sie auf dem System, auf dem Sie Unified Manager installieren, die Liste der verfügbaren und nicht verfügbaren Pakete an: `yum install *.rpm --assumeno`
+
Die Elemente im Abschnitt „`Installieren:`“ sind die Pakete, die im aktuellen Verzeichnis verfügbar sind, und die Elemente im Abschnitt „`Installieren für Abhängigkeiten:`“ sind die Pakete, die auf Ihrem System fehlen.

.. Laden Sie auf einem System mit Internetzugang die fehlenden Pakete herunter: `yum install <package_name\> --downloadonly --downloaddir=.`
+
[NOTE]
====
Da das Plug-in "`yum-Plugin-downloadonly`" nicht immer auf Red hat Enterprise Linux-Systemen aktiviert ist, müssen Sie möglicherweise die Funktionalität zum Herunterladen eines Pakets ohne Installation aktivieren: `yum install yum-plugin-downloadonly`

====
.. Kopieren Sie die fehlenden Pakete aus dem mit dem Internet verbundenen System auf Ihr Installationssystem.


. Installieren der Software: `yum install *.rpm`
+
Mit diesem Befehl wird der installiert `.rpm` Pakete, alle anderen erforderlichen unterstützende Software sowie die Unified Manager Software.

+
[NOTE]
====
Versuchen Sie nicht, die Installation mithilfe alternativer Befehle (z. B. `+rpm -ivh ...+`). Für die erfolgreiche Installation von Unified Manager auf einem Red hat Enterprise Linux- oder CentOS-System müssen alle Unified Manager-Dateien und zugehörigen Dateien in einer bestimmten Reihenfolge in eine bestimmte Verzeichnisstruktur installiert werden, die automatisch von der erzwungen wird `yum install *.rpm` Befehl.

====
. Ignorieren Sie die E-Mail-Benachrichtigung, die sofort nach den Installationsmeldungen angezeigt wird.
+
Die E-Mail informiert den Root-Benutzer über einen anfänglichen cron-Job-Fehler, der sich nicht nachteilig auf die Installation auswirkt.

. Nach Abschluss der Installationsmeldungen blättern Sie zurück zu den Meldungen, bis die Meldung angezeigt wird, in der das System eine IP-Adresse oder URL für die Web-UI von Unified Manager, den Wartungs-Benutzernamen (umadmin) und ein Standardpasswort anzeigt.
+
Die Meldung ähnelt der folgenden:

+
[listing]
----
OnCommand Unified Manager installed successfully.
Use a web browser and one of the following URL(s) to configure and access the Unified Manager GUI.
https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/

Log in to Unified Manager in a web browser by using following details:
  username: umadmin
  password: admin
----
. Notieren Sie die IP-Adresse oder URL, den zugewiesenen Benutzernamen (umadmin) und das aktuelle Passwort.
. Wenn Sie vor der Installation von Unified Manager ein umadmin-Benutzerkonto mit einem benutzerdefinierten Home-Verzeichnis erstellt haben, müssen Sie die Anmeldungs-Shell für umadmin-Benutzer angeben:``usermod -s /bin/maintenance-user-shell.sh umadmin``




== Nachdem Sie fertig sind

Sie können auf die Web-UI zugreifen, um die Ersteinrichtung von Unified Manager durchzuführen, wie im _OnCommand Unified Manager System Configuration Guide_ beschrieben.
