---
permalink: install/task-uninstalling-unified-manager-win.html 
sidebar: sidebar 
keywords:  
summary: Sie können Unified Manager von Windows deinstallieren, indem Sie den Assistenten Programme und Funktionen verwenden oder eine unbeaufsichtigte Deinstallation von der Befehlszeilenschnittstelle durchführen. 
---
= Deinstallieren von Unified Manager von Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:pp: &#43;&#43;


[role="lead"]
Sie können Unified Manager von Windows deinstallieren, indem Sie den Assistenten Programme und Funktionen verwenden oder eine unbeaufsichtigte Deinstallation von der Befehlszeilenschnittstelle durchführen.



== Bevor Sie beginnen

* Sie müssen über Administratorrechte für Windows verfügen.
* Alle Cluster (Datenquellen) müssen vom Unified Manager-Server entfernt werden, bevor die Software deinstalliert wird.
* Der Unified Manager-Server darf keine aktive Verbindung zu einem externen Datenanbieter wie Graphite haben.
+
In diesem Fall müssen Sie die Verbindung über die Unified ManagerMaintenance-Konsole löschen.





== Schritte

. Bei der Installation in einem Hochverfügbarkeitssetup sollten die Ressourcen der HA-Servicegruppe entfernt und die HA-Servicegruppe gelöscht werden, bevor Unified Manager von beiden Nodes deinstalliert wird.
. Deinstallieren Sie Unified Manager, indem Sie eine der folgenden Optionen auswählen:
+
|===
| So deinstallieren Sie Unified Manager über... | Dann... 


 a| 
Assistent Programme und Funktionen
 a| 
.. Navigieren Sie zu *Systemsteuerung* > *Programm und Funktionen*.
.. Wählen Sie OnCommand Unified Manager und klicken Sie auf *Deinstallieren*.




 a| 
Kommandozeile
 a| 
.. Melden Sie sich mit Administratorrechten an der Windows-Befehlszeile an.
.. Navigieren Sie zum Verzeichnis OnCommand Unified Manager, und führen Sie den folgenden Befehl aus: `+msiexec /x {A78760DB-7EC0-4305-97DB-E4A89CDFF4E1} /qn /l*v %systemdrive%\UmUnInstall.log+`


|===
+
Wenn die Benutzerkontensteuerung (UAC) auf dem Server aktiviert ist und Sie als Domänenbenutzer angemeldet sind, müssen Sie die Methode zur Deinstallation der Befehlszeile verwenden.

+
Unified Manager wird von Ihrem System deinstalliert.

. Deinstallieren Sie die folgenden Pakete und Daten von Drittanbietern, die während der Deinstallation von Unified Manager nicht entfernt werden:
+
** Pakete von Drittanbietern: JRE, MySQL, Microsoft Visual C&#43;&#43; 2015 Redistributable und 7zip
** MySQL Applikationsdaten von Unified Manager
** Anwendungsprotokolle und Inhalt des Applikationsdatenverzeichnisses



