---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: Sie können ein neues, benutzerdefiniertes JBoss-Kennwort erstellen, um das bei der Installation festgelegte Standardpasswort zu überschreiben. Diese Aufgabe ist optional, aber an einigen Standorten muss diese Sicherheitsfunktion möglicherweise die Standardeinstellung für die Unified Manager-Installation außer Kraft setzen. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet. 
---
= Ändern des JBoss-Passworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein neues, benutzerdefiniertes JBoss-Kennwort erstellen, um das bei der Installation festgelegte Standardpasswort zu überschreiben. Diese Aufgabe ist optional, aber an einigen Standorten muss diese Sicherheitsfunktion möglicherweise die Standardeinstellung für die Unified Manager-Installation außer Kraft setzen. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet.



== Bevor Sie beginnen

* Sie müssen Root-Zugriff auf das Red hat Enterprise Linux oder CentOS System haben, auf dem Unified Manager installiert ist.
* Sie müssen auf die von NetApp bereitgestellte Lösung zugreifen können `password.sh` Skript im Verzeichnis `/opt/netapp/essentials/bin`.




== Schritte

. Melden Sie sich als Root-Benutzer auf dem System an.
. Beenden Sie die Unified Manager Services, indem Sie die folgenden Befehle in der angezeigten Reihenfolge eingeben: `service ocieau stop``service ocie stop`
+
Beenden Sie die zugehörige MySQL-Software nicht.

. Geben Sie den folgenden Befehl ein, um den Passwortänderungsprozess zu starten: `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. Geben Sie bei Aufforderung das alte JBoss-Passwort ein.
+
Das Standardpasswort lautet `D11h1aMu@79%`.

. Geben Sie bei entsprechender Aufforderung das neue JBoss-Passwort ein und bestätigen Sie es anschließend erneut.
. Starten Sie nach Abschluss des Skripts die Unified Manager Services, indem Sie in der angezeigten Reihenfolge die folgenden Befehle eingeben: `service ocie start``service ocieau start`
. Nachdem alle Services gestartet wurden, können Sie sich in der UI von Unified Manager einloggen.

